# -*- coding: utf-8 -*-
"""0 Attention_HistoFusion_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N__4cBLQM4OsakHHXzer0X5tQgeqZVOM
"""

from google.colab import drive
drive.mount('/content/drive')

# Paths
DATASET_PATH = '/content/drive/MyDrive/breakhis_dataset/BreaKHis_v1/histology_slides/breast'

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import torch.optim as optim
from tqdm import tqdm

# ✅ Attention-based Fusion Module
class AttentionFusion(nn.Module):
    def __init__(self, in_dim=256, num_features=4):
        super(AttentionFusion, self).__init__()
        self.proj = nn.Linear(in_dim, in_dim)
        self.attn = nn.Linear(in_dim, 1)
        self.num_features = num_features

    def forward(self, features):
        # features: list of [B, in_dim] tensors
        stacked = torch.stack(features, dim=1)  # [B, num_features, in_dim]

        # projection + tanh
        proj = torch.tanh(self.proj(stacked))  # [B, num_features, in_dim]

        # attention scores
        attn_scores = self.attn(proj)  # [B, num_features, 1]
        attn_weights = F.softmax(attn_scores, dim=1)  # [B, num_features, 1]

        # weighted sum
        fused = torch.sum(attn_weights * stacked, dim=1)  # [B, in_dim]
        return fused


# ✅ Base CNN Backbone (ResNet50)
class MFF_CNN(nn.Module):
    def __init__(self, pretrained=True):
        super(MFF_CNN, self).__init__()
        resnet = models.resnet50(weights='DEFAULT' if pretrained else None)

        # Extract backbone blocks
        self.layer0 = nn.Sequential(resnet.conv1, resnet.bn1, resnet.relu, resnet.maxpool)
        self.layer1 = resnet.layer1  # 256-d
        self.layer2 = resnet.layer2  # 512-d
        self.layer3 = resnet.layer3  # 1024-d
        self.layer4 = resnet.layer4  # 2048-d

        # Projection layers to unify feature dims
        self.proj1 = nn.Conv2d(256, 256, kernel_size=1)
        self.proj2 = nn.Conv2d(512, 256, kernel_size=1)
        self.proj3 = nn.Conv2d(1024, 256, kernel_size=1)
        self.proj4 = nn.Conv2d(2048, 256, kernel_size=1)

        # Adaptive pooling
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Attention Fusion
        self.attn_fusion = AttentionFusion(in_dim=256, num_features=4)

    def forward(self, x):
        x0 = self.layer0(x)
        x1 = self.layer1(x0)
        x2 = self.layer2(x1)
        x3 = self.layer3(x2)
        x4 = self.layer4(x3)

        # Project + Pool
        f1 = self.global_pool(self.proj1(x1)).flatten(1)  # [B, 256]
        f2 = self.global_pool(self.proj2(x2)).flatten(1)  # [B, 256]
        f3 = self.global_pool(self.proj3(x3)).flatten(1)  # [B, 256]
        f4 = self.global_pool(self.proj4(x4)).flatten(1)  # [B, 256]

        # Attention Fusion (instead of concatenation)
        fused_features = self.attn_fusion([f1, f2, f3, f4])  # [B, 256]
        return fused_features


# ✅ QTN-like Feature Compression
class QTN_Layer(nn.Module):
    def __init__(self, input_dim=256, output_dim=128):
        super(QTN_Layer, self).__init__()
        self.compress = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Linear(512, output_dim),
            nn.ReLU()
        )

    def forward(self, x):
        return self.compress(x)


# ✅ Main Model with Attention Fusion
class MFF_HistoNet(nn.Module):
    def __init__(self, num_classes=2):
        super(MFF_HistoNet, self).__init__()
        self.cnn_backbone = MFF_CNN()

        # After attention fusion we get 256-d features
        self.qtn_layer = QTN_Layer(input_dim=256, output_dim=128)

        # Final classifier
        self.classifier = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(64, num_classes)
        )

    def forward(self, image):
        cnn_feat = self.cnn_backbone(image)
        qtn_feat = self.qtn_layer(cnn_feat)
        output = self.classifier(qtn_feat)
        return output


# ✅ Example Training Loop
if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_mff = MFF_HistoNet(num_classes=2).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model_mff.parameters(), lr=1e-4)

    print("Modified Attention-HistoFusion model instantiated.")

# Define the device (already defined in previous cells, but good to be explicit)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Instantiate the modified MFF_HistoNet model
# Make sure MFF_HistoNet class is defined in a previous cell and executed
model_mff = MFF_HistoNet(num_classes=len(class_names)).to(device) # Use the determined number of classes

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Define the device (already defined in previous cells, but good to be explicit)
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print(f"Using device: {device}")
# 
# # Instantiate the modified MFF_HistoNet model
# # Make sure MFF_HistoNet class is defined in a previous cell and executed
# model_mff = MFF_HistoNet(num_classes=len(class_names)).to(device) # Use the determined number of classes
# 
# # Define loss function and optimizer
# criterion_mff = nn.CrossEntropyLoss()
# optimizer_mff = optim.Adam(model_mff.parameters(), lr=0.0001) # Start with a slightly lower learning rate
# 
# # Training loop
# num_epochs_mff = 5
# print(f"Starting training for {num_epochs_mff} epochs with Attention-HistoFusion...")
# 
# # Lists to store metrics for plotting
# train_losses = []
# train_accuracies = []
# test_losses = []
# test_accuracies = []
# 
# 
# for epoch in range(num_epochs_mff):
#     model_mff.train() # Set the model to training mode
#     running_loss = 0.0
#     correct_train = 0
#     total_train = 0
# 
#     # Use tqdm for a progress bar during training
#     train_loader_tqdm = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs_mff} [Train]")
# 
#     # Modified line: accept three values from the DataLoader
#     for i, (inputs, labels, img_paths) in enumerate(train_loader_tqdm):
#         inputs, labels = inputs.to(device), labels.to(device)
# 
#         # Zero the parameter gradients
#         optimizer_mff.zero_grad()
# 
#         # Forward pass
#         outputs = model_mff(inputs)
#         loss = criterion_mff(outputs, labels)
# 
#         # Backward pass and optimize
#         loss.backward()
#         optimizer_mff.step()
# 
#         running_loss += loss.item() * inputs.size(0)
#         _, predicted = torch.max(outputs.data, 1)
#         total_train += labels.size(0)
#         correct_train += (predicted == labels).sum().item()
# 
#         # Update tqdm progress bar with current loss and accuracy
#         train_loader_tqdm.set_postfix(loss=running_loss/total_train, acc=100. * correct_train / total_train)
# 
# 
#     epoch_loss = running_loss / len(train_dataset)
#     epoch_acc = 100 * correct_train / total_train
#     train_losses.append(epoch_loss) # Store training loss
#     train_accuracies.append(epoch_acc) # Store training accuracy
# 
# 
#     print(f"Epoch [{epoch+1}/{num_epochs_mff}], Train Loss: {epoch_loss:.4f}, Train Acc: {epoch_acc:.2f}%")
# 
#     # Evaluation on the test set
#     model_mff.eval() # Set the model to evaluation mode
#     correct_test = 0
#     total_test = 0
#     running_test_loss = 0.0 # Track test loss as well
# 
#     # Use tqdm for a progress bar during evaluation
#     test_loader_tqdm = tqdm(test_loader, desc=f"Epoch {epoch+1}/{num_epochs_mff} [Test]")
# 
#     with torch.no_grad(): # Disable gradient calculation for evaluation
#         # Modified line: accept three values from the DataLoader
#         for inputs, labels, img_paths in test_loader_tqdm:
#             inputs, labels = inputs.to(device), labels.to(device)
#             outputs = model_mff(inputs)
#             loss = criterion_mff(outputs, labels) # Calculate test loss
# 
#             running_test_loss += loss.item() * inputs.size(0)
#             _, predicted = torch.max(outputs.data, 1)
#             total_test += labels.size(0)
#             correct_test += (predicted == labels).sum().item()
# 
#             # Update tqdm progress bar with current accuracy
#             test_loader_tqdm.set_postfix(acc=100. * correct_test / total_test)
# 
# 
#     test_loss = running_test_loss / len(test_dataset) # Calculate average test loss
#     test_acc = 100 * correct_test / total_test
#     test_losses.append(test_loss) # Store test loss
#     test_accuracies.append(test_acc) # Store test accuracy
# 
# 
#     print(f"Epoch [{epoch+1}/{num_epochs_mff}], Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.2f}%")
# 
# 
# print("Finished Training with Attention-HistoFusion")
# 
# # Save the model state dictionary
# torch.save(model_mff.state_dict(), '/content/drive/MyDrive/breakhis_dataset/Attention-HistoFusion_patient.pth')
# print("Attention-HistoFusion model state dictionary saved to /content/drive/MyDrive/breakhis_dataset/Attention-HistoFusion_patient.pth")

import torch
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set the model to evaluation mode
model_mff.eval()

all_labels = []
all_predictions = []
all_probabilities = [] # List to store probabilities

# Disable gradient calculation for evaluation
with torch.no_grad():
    for inputs, labels, img_paths in tqdm(test_loader, desc="Evaluating Model"): # Modified line: accept three values
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model_mff(inputs)
        _, predicted = torch.max(outputs.data, 1)

        # Get probabilities (apply softmax if needed, but CrossEntropyLoss includes softmax internally)
        # For binary classification with CrossEntropyLoss, the output is typically logits.
        # We can use softmax to get probabilities, or just use the logits of the positive class.
        # Let's use softmax to be more explicit.
        probabilities = torch.softmax(outputs, dim=1)[:, 1] # Probability of the positive class (malignant is class 1)


        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())
        all_probabilities.extend(probabilities.cpu().numpy()) # Store probabilities

import matplotlib.pyplot as plt

# Plot training and validation loss (Separate Figure)
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(train_losses) + 1), train_losses, marker='o', linestyle='-', label='Train Loss', linewidth=2)
plt.plot(range(1, len(test_losses) + 1), test_losses, marker='s', linestyle='-', label='Test Loss', linewidth=2)
plt.xlabel('Epoch', weight='bold', fontsize=12)
plt.ylabel('Loss', weight='bold', fontsize=12)
plt.title('Training and Test Loss per Epoch for Attention-HistoFusion model', weight='bold', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.xticks(range(1, 6))
plt.tight_layout()
plt.show()

# Plot training and validation accuracy (Separate Figure)
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(train_accuracies) + 1), train_accuracies, marker='o', linestyle='-', label='Train Accuracy', linewidth=2)
plt.plot(range(1, len(test_accuracies) + 1), test_accuracies, marker='s', linestyle='-', label='Test Accuracy', linewidth=2)
plt.xlabel('Epoch', weight='bold', fontsize=12)
plt.ylabel('Accuracy (%)', weight='bold', fontsize=12)
plt.title('Training and Test Accuracy per Epoch for Attention-HistoFusion model', weight='bold', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.ylim(80, 100)  # Set y-axis limits to better visualize the accuracy range
plt.xticks(range(1, 6))
plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Calculate ROC curve and AUC
fpr, tpr, thresholds = roc_curve(all_labels, all_probabilities)
roc_auc = auc(fpr, tpr)

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate',weight='bold')
plt.ylabel('True Positive Rate',weight='bold')
plt.title('Receiver Operating Characteristic (ROC) Curve for Attention-HistoFusion model',weight='bold')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print(f"AUC: {roc_auc:.4f}")

from sklearn.metrics import precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt

# Calculate Precision-Recall curve and Average Precision Score
precision, recall, _ = precision_recall_curve(all_labels, all_probabilities)
average_precision = average_precision_score(all_labels, all_probabilities)

# Plot Precision-Recall curve
plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='darkorange', lw=2, label='Precision-Recall curve (AP = %0.2f)' % average_precision)
plt.xlabel('Recall',weight='bold')
plt.ylabel('Precision',weight='bold')
plt.title('Precision-Recall Curve for Attention-HistoFusion model',weight='bold')
plt.legend(loc="lower left")
plt.grid(True)
plt.show()

print(f"Average Precision (AP): {average_precision:.4f}")

import torch
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Convert lists to numpy arrays
all_labels = np.array(all_labels)
all_predictions = np.array(all_predictions)

# Generate Confusion Matrix
conf_matrix = confusion_matrix(all_labels, all_predictions)
total_samples = conf_matrix.sum()

print("\nConfusion Matrix:")
print(conf_matrix)

# Calculate percentages (row-wise)
conf_matrix_percent = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]

# Calculate percentage of total samples
conf_matrix_total_percent = conf_matrix / total_samples

# Create enhanced annotations with color control
class_names = ['benign', 'malignant']

# Prepare annotations with white color for TP cell
annotations = [
    [f"TN: {conf_matrix[0,0]}\n({conf_matrix_percent[0,0]:.1%})\n{conf_matrix_total_percent[0,0]:.1%}",
     f"FP: {conf_matrix[0,1]}\n({conf_matrix_percent[0,1]:.1%})\n{conf_matrix_total_percent[0,1]:.1%}"],
    [f"FN: {conf_matrix[1,0]}\n({conf_matrix_percent[1,0]:.1%})\n{conf_matrix_total_percent[1,0]:.1%}",
     f"TP: {conf_matrix[1,1]}\n({conf_matrix_percent[1,1]:.1%})\n{conf_matrix_total_percent[1,1]:.1%}"]
]

# Create a mask for TP cell to apply white color
annot_colors = [["black", "black"], ["black", "white"]]  # Colors for [TN, FP], [FN, TP]

# Plot Confusion Matrix with larger text
plt.rcParams.update({'font.size': 14})
fig, ax = plt.subplots(figsize=(10, 8))

# Create heatmap with custom text colors
heatmap = sns.heatmap(
    conf_matrix,
    annot=annotations,
    fmt='',
    cmap='Blues',
    annot_kws={"size": 16, "weight": "bold"},
    xticklabels=class_names,
    yticklabels=class_names,
    ax=ax,
    linewidths=0.5,
    linecolor='gray',
    cbar=True,
    square=True
)

# Manually set text colors after creating the heatmap
for i, text_row in enumerate(heatmap.texts):
    # The texts are ordered by row then column
    if i == 3:  # TP cell (last cell)
        text_row.set_color("white")
    else:
        text_row.set_color("black")

# Customize colorbar
cbar = heatmap.collections[0].colorbar
cbar.ax.tick_params(labelsize=14)
cbar.set_label('Number of Samples', fontsize=16, weight='bold')

# Axis labels with larger font
ax.set_xlabel('Predicted Label', fontsize=16, weight='bold')
ax.set_ylabel('True Label', fontsize=16, weight='bold')
ax.set_title('Confusion Matrix for Attention-HistoFusion model', fontsize=18, weight='bold')

# Customize tick labels
ax.set_xticklabels(class_names, fontsize=14, weight='bold')
ax.set_yticklabels(class_names, fontsize=14, weight='bold', rotation=0)

# Adjust layout
plt.tight_layout()

# Display the figure
plt.show()

# Generate Classification Report
print("\nClassification Report:")
print(classification_report(all_labels, all_predictions, target_names=class_names))

from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Calculate Precision, Recall, and F1-Score (for the positive class, which is 'malignant' based on class_names and labels_encoded)
# Assuming 'malignant' is the positive class (label 1)
precision = precision_score(all_labels, all_predictions, pos_label=1)
recall = recall_score(all_labels, all_predictions, pos_label=1)
f1 = f1_score(all_labels, all_predictions, pos_label=1)

# Calculate Cohen's Kappa Score
kappa = cohen_kappa_score(all_labels, all_predictions)

print(f"Precision (PPV) for Malignant: {precision:.4f}")
print(f"Recall (Sensitivity) for Malignant: {recall:.4f}")
print(f"F1-Score for Malignant: {f1:.4f}")
print(f"Cohen's Kappa Score: {kappa:.4f}")

import numpy as np
from scipy.stats import pearsonr, chi2_contingency, f_oneway
from sklearn.metrics import confusion_matrix

# Ensure all_labels and all_probabilities are numpy arrays from previous evaluation cell (d9df1b4b)
# They are already converted to numpy arrays in cell -vhLke3GSj2Y, but let's ensure for this cell's operations.
all_labels = np.array(all_labels, dtype=int) # Ensure integer type
all_probabilities = np.array(all_probabilities)


# 1. Pearson Correlation Coefficient and P-value
# Calculate correlation between true binary labels (0 or 1) and predicted probabilities
# This might not be the most standard use, but can show if higher probabilities correlate with the positive class
pearson_corr, pearson_p_value = pearsonr(all_labels, all_probabilities)
print(f"Pearson Correlation Coefficient between True Labels and Predicted Probabilities: {pearson_corr:.4f}")
print(f"Pearson P-value: {pearson_p_value:.4f}")

# 2. Chi-Square Statistic and P-value
# Applied to the confusion matrix to test for independence between true and predicted classes
conf_matrix = confusion_matrix(all_labels, all_predictions)
chi2_stat, chi2_p_value, _, _ = chi2_contingency(conf_matrix)
print(f"\nChi-Square Statistic on Confusion Matrix: {chi2_stat:.4f}")
print(f"Chi-Square P-value: {chi2_p_value:.4f}")

# 3. ANOVA F-Statistic and P-value
# Compare the mean of predicted probabilities for the positive class between the two true classes
# Separate predicted probabilities based on true class
prob_benign = all_probabilities[all_labels == 0]
prob_malignant = all_probabilities[all_labels == 1]

# Perform one-way ANOVA
# Check if there are enough samples in each group
if len(prob_benign) > 1 and len(prob_malignant) > 1:
    anova_f_statistic, anova_p_value = f_oneway(prob_benign, prob_malignant)
    print(f"\nANOVA F-Statistic (Predicted Probabilities vs. True Class): {anova_f_statistic:.4f}")
    print(f"ANOVA P-value: {anova_p_value:.4f}")
else:
    print("\nNot enough samples in one or both classes to perform ANOVA.")

import torch
import time
import os
import psutil # Library to get system and process information

# Ensure model is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mff.to(device)
model_mff.eval()

# Get a single sample from the test dataset
# Make sure test_dataset is defined from previous steps
if len(test_dataset) > 0:
    sample_input, sample_label, _ = test_dataset[0] # Get the first sample

    # Add batch dimension and move to device
    sample_input = sample_input.unsqueeze(0).to(device)

    # --- Measure Memory Usage ---
    process = psutil.Process(os.getpid())

    # Initial memory usage
    initial_memory = process.memory_info().rss / (1024 * 1024) # in MB
    print(f"Initial Memory Usage: {initial_memory:.2f} MB")

    # --- Measure Inference Time ---
    # Warm-up run (optional, but good practice for timing)
    with torch.no_grad():
        _ = model_mff(sample_input)

    # Measure time
    start_time = time.time()
    with torch.no_grad():
        output = model_mff(sample_input)
    end_time = time.time()

    inference_time = end_time - start_time
    print(f"Inference Time: {inference_time:.6f} seconds")

    # Peak memory usage during inference is harder to measure precisely within a single script run like this
    # The psutil memory_info().rss gives current resident set size, not peak during a specific operation.
    # More advanced tools or profiling might be needed for accurate peak memory during inference.
    # For simplicity, we'll just print the current memory after inference.
    # Peak memory during inference is generally between initial and final memory if no large objects are freed.
    final_memory = process.memory_info().rss / (1024 * 1024) # in MB
    print(f"Memory Usage After Inference: {final_memory:.2f} MB")

    # A more relevant "Peak Memory" might be the difference if run in isolation or using specific profiling tools.
    # As a rough estimate, one could consider the difference, but it's not truly "peak during inference".
    # print(f"Estimated Memory Increase during Inference: {final_memory - initial_memory:.2f} MB")

else:
    print("Test dataset is empty, cannot measure inference time and memory.")

import torch
import torch.nn.functional as F
import numpy as np
import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

# Ensure the model is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mff.to(device)
model_mff.eval()

# Choose a target layer for Grad-CAM
# We'll use the last convolutional layer before the pooling/classifier
# In ResNet50 backbone (used in MFF_CNN), layer4 is the last convolutional block
target_layer = model_mff.cnn_backbone.layer4[-1] # Use the last block of layer4

# Function to register hooks for Grad-CAM
def register_hooks(model, target_layer):
    # Stores the feature maps
    feature_maps = []
    # Stores the gradients of the target output w.r.t. the feature maps
    gradients = []

    def save_feature_maps(module, input, output):
        feature_maps.append(output)

    def save_gradients(module, grad_in, grad_out):
        # grad_out is a tuple, we need the gradient w.r.t. the output
        gradients.append(grad_out[0])

    # Register hooks
    hook_handle_fm = target_layer.register_forward_hook(save_feature_maps)
    hook_handle_grad = target_layer.register_backward_hook(save_gradients)

    return feature_maps, gradients, hook_handle_fm, hook_handle_grad

# Function to generate Grad-CAM heatmap
def generate_grad_cam(image, model, target_layer, target_class=None):
    feature_maps, gradients, hook_fm, hook_grad = register_hooks(model, target_layer)

    # Add batch dimension and move to device
    input_tensor = image.unsqueeze(0).to(device)

    # Forward pass
    output = model(input_tensor)

    # Get the predicted class
    predicted_class = output.argmax(dim=1).item()

    # If target_class is not specified, use the predicted class
    if target_class is None:
        target_class = predicted_class

    # Zero gradients
    model.zero_grad()

    # Backward pass to get gradients w.r.t. the target class output
    target_output = output[0, target_class]
    target_output.backward()

    # Get the feature maps and gradients
    feature_map = feature_maps[0].squeeze(0)
    gradient = gradients[0].squeeze(0)

    # Deregister hooks
    hook_fm.remove()
    hook_grad.remove()

    # Calculate the weights (global average pooling of gradients)
    weights = torch.mean(gradient, dim=(1, 2), keepdim=True)

    # Compute the CAM
    cam = torch.sum(weights * feature_map, dim=0)

    # Apply ReLU to the CAM
    cam = F.relu(cam)

    # Normalize the CAM to be between 0 and 1
    cam = cam / torch.max(cam)

    # Convert CAM to numpy array and resize to input image size
    cam_np = cam.detach().cpu().numpy()
    h, w = image.shape[1:] # Get original image height and width
    cam_resized = cv2.resize(cam_np, (w, h))

    return cam_resized, predicted_class, target_class

# Function to display the image with Grad-CAM heatmap
def display_grad_cam(image, heatmap, title="Grad-CAM"):
    # Convert image tensor to numpy and denormalize/transpose if needed
    # Assuming image is already normalized and in (C, H, W) format
    # Convert to (H, W, C) and denormalize if necessary for display
    image_np = image.permute(1, 2, 0).cpu().numpy()

    # Denormalize the image if it was normalized (e.g., by dividing by 255.0)
    # If simple_normalize divided by 255, we multiply by 255 here
    # If ToTensorV2 normalized to [0, 1], no denormalization needed here for display

    # Ensure image_np is in uint8 for overlay
    # If image_np is float [0, 1], convert to uint8 [0, 255]
    image_np_uint8 = (image_np * 255).astype(np.uint8)


    # Apply heatmap color map
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)

    # Overlay heatmap on the original image
    # Use cv2.addWeighted for alpha blending
    overlayed_image = cv2.addWeighted(image_np_uint8, 0.6, heatmap_colored, 0.4, 0)

    # Display the images
    fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # Increased figsize


    axes[0].imshow(image_np_uint8)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    axes[1].imshow(heatmap, cmap='jet')
    axes[1].set_title("Grad-CAM Heatmap")
    axes[1].axis('off')

    axes[2].imshow(overlayed_image)
    axes[2].set_title(title)
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

# --- Example Usage ---
# Get a sample image from the test dataset
if len(test_dataset) > 0:
    # Get the first image and label from the test dataset
    sample_image, true_label, _ = test_dataset[0]
    true_label_name = class_names[true_label] # Get the class name

    print(f"Processing sample with True Label: {true_label_name}")

    # Generate Grad-CAM heatmap for the predicted class
    heatmap, predicted_class_idx, target_class_idx = generate_grad_cam(sample_image, model_mff, target_layer)
    predicted_class_name = class_names[predicted_class_idx]
    target_class_name = class_names[target_class_idx]


    print(f"Model Predicted Class: {predicted_class_name}")
    print(f"Grad-CAM generated for Target Class: {target_class_name}")


    # Display the results
    display_grad_cam(sample_image, heatmap, title=f"Grad-CAM for Predicted Class: {predicted_class_name}")

    # Optional: Generate Grad-CAM for the true class (if different from predicted)
    if predicted_class_idx != true_label:
        print(f"\nGenerating Grad-CAM for True Class: {true_label_name}")
        heatmap_true_class, _, _ = generate_grad_cam(sample_image, model_mff, target_layer, target_class=true_label)
        display_grad_cam(sample_image, heatmap_true_class, title=f"Grad-CAM for True Class: {true_label_name}")


else:
    print("Test dataset is empty, cannot perform Grad-CAM.")

import torch
import torch.nn.functional as F
import numpy as np
import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

# Ensure the model is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mff.to(device)
model_mff.eval()

# Choose a target layer for Grad-CAM
# We'll use the last convolutional layer before the pooling/classifier
# In ResNet50 backbone (used in MFF_CNN), layer4 is the last convolutional block
target_layer = model_mff.cnn_backbone.layer4[-1] # Use the last block of layer4

# Function to register hooks for Grad-CAM
def register_hooks(model, target_layer):
    # Stores the feature maps
    feature_maps = []
    # Stores the gradients of the target output w.r.t. the feature maps
    gradients = []

    def save_feature_maps(module, input, output):
        feature_maps.append(output)

    def save_gradients(module, grad_in, grad_out):
        # grad_out is a tuple, we need the gradient w.r.t. the output
        gradients.append(grad_out[0])

    # Register hooks
    hook_handle_fm = target_layer.register_forward_hook(save_feature_maps)
    hook_handle_grad = target_layer.register_backward_hook(save_gradients)

    return feature_maps, gradients, hook_handle_fm, hook_handle_grad

# Function to generate Grad-CAM heatmap
def generate_grad_cam(image, model, target_layer, target_class=None):
    feature_maps, gradients, hook_fm, hook_grad = register_hooks(model, target_layer)

    # Add batch dimension and move to device
    input_tensor = image.unsqueeze(0).to(device)

    # Forward pass
    output = model(input_tensor)

    # Get the predicted class
    predicted_class = output.argmax(dim=1).item()

    # If target_class is not specified, use the predicted class
    if target_class is None:
        target_class = predicted_class

    # Zero gradients
    model.zero_grad()

    # Backward pass to get gradients w.r.t. the target class output
    target_output = output[0, target_class]
    target_output.backward()

    # Get the feature maps and gradients
    feature_map = feature_maps[0].squeeze(0)
    gradient = gradients[0].squeeze(0)

    # Deregister hooks
    hook_fm.remove()
    hook_grad.remove()

    # Calculate the weights (global average pooling of gradients)
    weights = torch.mean(gradient, dim=(1, 2), keepdim=True)

    # Compute the CAM
    cam = torch.sum(weights * feature_map, dim=0)

    # Apply ReLU to the CAM
    cam = F.relu(cam)

    # Normalize the CAM to be between 0 and 1
    cam = cam / torch.max(cam)

    # Convert CAM to numpy array and resize to input image size
    cam_np = cam.detach().cpu().numpy()
    h, w = image.shape[1:] # Get original image height and width
    cam_resized = cv2.resize(cam_np, (w, h))

    return cam_resized, predicted_class, target_class

# Function to display the image with Grad-CAM heatmap
def display_grad_cam(image, heatmap, title="Grad-CAM"):
    # Convert image tensor to numpy and denormalize/transpose if needed
    # Assuming image is already normalized and in (C, H, W) format
    # Convert to (H, W, C) and denormalize if necessary for display
    image_np = image.permute(1, 2, 0).cpu().numpy()

    # Denormalize the image if it was normalized (e.g., by dividing by 255.0)
    # If simple_normalize divided by 255, we multiply by 255 here
    # If ToTensorV2 normalized to [0, 1], no denormalization needed here for display

    # Ensure image_np is in uint8 for overlay
    # If image_np is float [0, 1], convert to uint8 [0, 255]
    image_np_uint8 = (image_np * 255).astype(np.uint8)


    # Apply heatmap color map
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)

    # Overlay heatmap on the original image
    # Use cv2.addWeighted for alpha blending
    overlayed_image = cv2.addWeighted(image_np_uint8, 0.6, heatmap_colored, 0.4, 0)

    # Display the images
    fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # Increased figsize


    axes[0].imshow(image_np_uint8)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    axes[1].imshow(heatmap, cmap='jet')
    axes[1].set_title("Grad-CAM Heatmap")
    axes[1].axis('off')

    axes[2].imshow(overlayed_image)
    axes[2].set_title(title)
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

# --- Example Usage ---
# Get a sample image from the test dataset
# We'll pick a different index than 0
sample_index = 5

if len(test_dataset) > sample_index:
    # Get the image and label from the test dataset at the specified index
    sample_image, true_label, _ = test_dataset[sample_index]
    true_label_name = class_names[true_label] # Get the class name

    print(f"Processing sample {sample_index} with True Label: {true_label_name}")

    # Generate Grad-CAM heatmap for the predicted class
    heatmap, predicted_class_idx, target_class_idx = generate_grad_cam(sample_image, model_mff, target_layer)
    predicted_class_name = class_names[predicted_class_idx]
    target_class_name = class_names[target_class_idx]


    print(f"Model Predicted Class: {predicted_class_name}")
    print(f"Grad-CAM generated for Target Class: {target_class_name}")


    # Display the results
    display_grad_cam(sample_image, heatmap, title=f"Grad-CAM for Predicted Class: {predicted_class_name} (Sample {sample_index})")

    # Optional: Generate Grad-CAM for the true class (if different from predicted)
    if predicted_class_idx != true_label:
        print(f"\nGenerating Grad-CAM for True Class: {true_label_name} (Sample {sample_index})")
        heatmap_true_class, _, _ = generate_grad_cam(sample_image, model_mff, target_layer, target_class=true_label)
        display_grad_cam(sample_image, heatmap_true_class, title=f"Grad-CAM for True Class: {true_label_name} (Sample {sample_index})")

else:
    print(f"Test dataset does not have a sample at index {sample_index}.")

import numpy as np
import torch
import torch.nn.functional as F
import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

# Ensure all_labels and all_predictions are available from previous evaluation (cell d9df1b4b)
# all_labels = np.array(...)
# all_predictions = np.array(...)

# Find indices of misclassified samples in the test set
misclassified_indices = np.where(all_labels != all_predictions)[0]

print(f"Found {len(misclassified_indices)} misclassified samples in the test set.")

# Select a few misclassified samples to visualize with Grad-CAM
num_samples_to_visualize = 3 # Adjust as needed

if len(misclassified_indices) > 0:
    # Take up to num_samples_to_visualize from the misclassified indices
    selected_misclassified_indices = misclassified_indices[:num_samples_to_visualize]

    print(f"Visualizing Grad-CAM for {len(selected_misclassified_indices)} misclassified samples:")

    # Make sure the Grad-CAM functions (generate_grad_cam, display_grad_cam)
    # and model_mff, target_layer, device, class_names are defined in previous cells

    for i, test_dataset_index in enumerate(selected_misclassified_indices):
        print(f"\nProcessing misclassified sample {i+1}/{len(selected_misclassified_indices)} (Original test_dataset index: {test_dataset_index})")

        # Get the image and label from the test dataset using the original index
        sample_image, true_label,_ = test_dataset[test_dataset_index]
        true_label_name = class_names[true_label] # Get the true class name
        predicted_label_name = class_names[all_predictions[test_dataset_index]] # Get the predicted class name


        print(f"  True Label: {true_label_name}, Predicted Label: {predicted_label_name}")

        # Generate Grad-CAM heatmap for the predicted class
        heatmap, predicted_class_idx, target_class_idx = generate_grad_cam(sample_image, model_mff, target_layer)
        # predicted_class_name is already available as predicted_label_name
        # target_class_name = class_names[target_class_idx]


        # Display the results
        # Include true and predicted labels in the title
        display_grad_cam(sample_image, heatmap, title=f"Grad-CAM (Misclassified): True: {true_label_name}, Predicted: {predicted_label_name}")

        # Optional: Generate Grad-CAM for the true class as well for comparison
        # This might show what the model *should* have focused on
        if predicted_class_idx != true_label:
             print(f"  Generating Grad-CAM for True Class ({true_label_name}) for comparison:")
             heatmap_true_class, _, _ = generate_grad_cam(sample_image, model_mff, target_layer, target_class=true_label)
             display_grad_cam(sample_image, heatmap_true_class, title=f"Grad-CAM (Misclassified, Target True): True: {true_label_name}, Predicted: {predicted_label_name}")


else:
    print("No misclassified samples found to visualize.")

import numpy as np
from sklearn.metrics import confusion_matrix

# Ensure all_labels and all_predictions are available from previous evaluation (cell d9df1b4b)
# all_labels = np.array(...)
# all_predictions = np.array(...)

# Calculate the total number of misclassified samples
misclassified_count = np.sum(all_labels != all_predictions)

print(f"Total number of misclassified samples: {misclassified_count}")

# Get the confusion matrix again to extract FN and FP counts
# Rows are True Labels, Columns are Predicted Labels
# [[TN, FP],
#  [FN, TP]]
conf_matrix = confusion_matrix(all_labels, all_predictions)

tn, fp, fn, tp = conf_matrix.ravel()

print("\nBreakdown of Misclassifications:")
print(f"  False Positives (FP): {fp} (Model predicted Malignant, but it was Benign)")
print(f"  False Negatives (FN): {fn} (Model predicted Benign, but it was Malignant)")

# Calculate Misclassification Rates
# False Positive Rate (FPR): FP / (FP + TN) - Proportion of actual negatives incorrectly classified as positive
# False Negative Rate (FNR): FN / (FN + TP) - Proportion of actual positives incorrectly classified as negative (Type II error)

fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
fnr = fn / (fn + tp) if (fn + tp) > 0 else 0

print("\nMisclassification Rates:")
print(f"  False Positive Rate (FPR): {fpr:.4f}")
print(f"  False Negative Rate (FNR): {fnr:.4f} (Type II Error Rate)")

# Recall (Sensitivity) is 1 - FNR
# Specificity is 1 - FPR
# We've already calculated these in the classification report and specific metrics cell, but reiterating here for clarity
recall_malignant = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity_benign = tn / (tn + fp) if (tn + fp) > 0 else 0

print("\nRelated Metrics for Context:")
print(f"  Recall (Sensitivity) for Malignant: {recall_malignant:.4f}")
print(f"  Specificity for Benign: {specificity_benign:.4f}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure all_probabilities and all_labels are available from previous evaluation (cell d9df1b4b or hG5UgVT59kYz)
# and convert them to numpy arrays if they are lists
all_probabilities = np.array(all_probabilities) # Ensure all_probabilities is a numpy array
all_labels = np.array(all_labels) # Ensure all_labels is a numpy array
all_predictions = np.array(all_predictions) # Ensure all_predictions is a numpy array

# Calculate confidence for the predicted class
# For binary classification, the probability of the predicted class is:
# - all_probabilities for the positive class (malignant)
# - 1 - all_probabilities for the negative class (benign)
predicted_confidences = np.where(all_predictions == 1, all_probabilities, 1 - all_probabilities)

# Separate confidences for correct and incorrect predictions
correctly_predicted_confidences = predicted_confidences[all_labels == all_predictions]
incorrectly_predicted_confidences = predicted_confidences[all_labels != all_predictions]

print("Analysis of Prediction Confidence:")
print(f"  Average confidence for correctly predicted samples: {np.mean(correctly_predicted_confidences):.4f}" if len(correctly_predicted_confidences) > 0 else "  No correctly predicted samples.")
print(f"  Average confidence for incorrectly predicted samples: {np.mean(incorrectly_predicted_confidences):.4f}" if len(incorrectly_predicted_confidences) > 0 else "  No incorrectly predicted samples.")


print("\nConfidence distribution for correctly predicted samples:")
if len(correctly_predicted_confidences) > 0:
    print(f"  Min: {np.min(correctly_predicted_confidences):.4f}")
    print(f"  Max: {np.max(correctly_predicted_confidences):.4f}")
    print(f"  Median: {np.median(correctly_predicted_confidences):.4f}")
    print(f"  Std Dev: {np.std(correctly_predicted_confidences):.4f}")
else:
    print("  No correctly predicted samples to analyze.")


print("\nConfidence distribution for incorrectly predicted samples:")
if len(incorrectly_predicted_confidences) > 0:
    print(f"  Min: {np.min(incorrectly_predicted_confidences):.4f}")
    print(f"  Max: {np.max(incorrectly_predicted_confidences):.4f}")
    print(f"  Median: {np.median(incorrectly_predicted_confidences):.4f}")
    print(f"  Std Dev: {np.std(incorrectly_predicted_confidences):.4f}")
else:
    print("  No incorrectly predicted samples found.")


# Separate confidences by true class
benign_confidences = predicted_confidences[all_labels == 0]
malignant_confidences = predicted_confidences[all_labels == 1]

print("\nConfidence distribution by True Class:")
print(f"  Average confidence for True Benign samples: {np.mean(benign_confidences):.4f}" if len(benign_confidences) > 0 else "  No True Benign samples.")
print(f"  Average confidence for True Malignant samples: {np.mean(malignant_confidences):.4f}" if len(malignant_confidences) > 0 else "  No True Malignant samples.")

print("\nConfidence distribution for True Benign samples:")
if len(benign_confidences) > 0:
    print(f"  Min: {np.min(benign_confidences):.4f}")
    print(f"  Max: {np.max(benign_confidences):.4f}")
    print(f"  Median: {np.median(benign_confidences):.4f}")
    print(f"  Std Dev: {np.std(benign_confidences):.4f}")
else:
    print("  No True Benign samples to analyze.")

print("\nConfidence distribution for True Malignant samples:")
if len(malignant_confidences) > 0:
    print(f"  Min: {np.min(malignant_confidences):.4f}")
    print(f"  Max: {np.max(malignant_confidences):.4f}")
    print(f"  Median: {np.median(malignant_confidences):.4f}")
    print(f"  Std Dev: {np.std(malignant_confidences):.4f}")
else:
    print("  No True Malignant samples to analyze.")

