# -*- coding: utf-8 -*-
"""1 VASI-Justifications.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKy-nhqzvcyey7bwTPXFKncCoRqH35Zn
"""

import numpy as np
from scipy.special import gamma
import pandas as pd
import matplotlib.pyplot as plt
import random
random.seed(42)
np.random.seed(42)

# Test Functions (based on scientific benchmarks)
def sphere(x):
    return np.sum(x**2, axis=1)

def rastrigin(x):
    A = 10
    return A * x.shape[1] + np.sum(x**2 - A * np.cos(2 * np.pi * x), axis=1)

def ackley(x):
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = x.shape[1]
    sum_sq = np.sum(x**2, axis=1)
    sum_cos = np.sum(np.cos(c * x), axis=1)
    return -a * np.exp(-b * np.sqrt(sum_sq / d)) - np.exp(sum_cos / d) + a + np.exp(1)

# ---------------------------
# Standard PSO (Kennedy & Eberhart)
# ---------------------------
def pso(N, T, d, lb, ub, obj_func, w_max=0.9, w_min=0.4, c1=2.0, c2=2.0):
    x = np.random.uniform(lb, ub, (N, d))
    v = np.zeros((N, d))
    pbest = x.copy()
    pbest_fitness = obj_func(x)
    gbest_idx = np.argmin(pbest_fitness)
    gbest = pbest[gbest_idx].copy()
    gbest_fitness = pbest_fitness[gbest_idx]
    fitness_history = [gbest_fitness]

    for t in range(T):
        w = w_max - (w_max - w_min) * (t / T)
        r1 = np.random.uniform(0, 1, (N, d))
        r2 = np.random.uniform(0, 1, (N, d))
        v = w * v + c1 * r1 * (pbest - x) + c2 * r2 * (gbest - x)
        x = x + v
        x = np.clip(x, lb, ub)
        fitness = obj_func(x)
        update_mask = fitness < pbest_fitness
        pbest[update_mask] = x[update_mask]
        pbest_fitness[update_mask] = fitness[update_mask]
        current_best_idx = np.argmin(pbest_fitness)
        if pbest_fitness[current_best_idx] < gbest_fitness:
            gbest = pbest[current_best_idx].copy()
            gbest_fitness = pbest_fitness[current_best_idx]
        fitness_history.append(gbest_fitness)

    return gbest, gbest_fitness, fitness_history

# ---------------------------
# WSO Implementation
# ---------------------------
def wso(N, T, d, lb, ub, obj_func, a=2.0, b=0.5):
    x = np.random.uniform(lb, ub, (N, d))
    fitness = obj_func(x)
    gbest_idx = np.argmin(fitness)
    gbest = x[gbest_idx].copy()
    gbest_fitness = fitness[gbest_idx]
    fitness_history = [gbest_fitness]

    for t in range(T):
        a_current = a * (1 - t / T)
        for i in range(N):
            r = np.random.uniform(0, 1)
            A = 2 * a_current * r - a_current
            C = 2 * r
            p = np.random.uniform(0, 1)
            if p < 0.5:
                if abs(A) < 1:
                    D = np.abs(C * gbest - x[i])
                    x[i] = gbest - A * D
                else:
                    rand_whale = x[np.random.randint(0, N)]
                    D = np.abs(C * rand_whale - x[i])
                    x[i] = rand_whale - A * D
            else:
                distance_to_best = np.abs(gbest - x[i])
                # ensure numerical stability: cap distance
                distance_to_best = np.clip(distance_to_best, 1e-12, np.inf)
                x[i] = distance_to_best * np.exp(b * distance_to_best) * np.cos(2 * np.pi * distance_to_best) + gbest
            x[i] = np.clip(x[i], lb, ub)
        fitness = obj_func(x)
        current_best_idx = np.argmin(fitness)
        if fitness[current_best_idx] < gbest_fitness:
            gbest = x[current_best_idx].copy()
            gbest_fitness = fitness[current_best_idx]
        fitness_history.append(gbest_fitness)

    return gbest, gbest_fitness, fitness_history

# ---------------------------
# VASI++ Improved Implementation
# ---------------------------
def vasi_plus_plus_v2(N, T, d, lb, ub, obj_func,
                      w_max=0.9, w_min=0.4, c1=1.5, c2=1.5,
                      alpha=0.08, beta=0.15, v_th=0.5, mu=1.5, b=1.0,
                      p_min=0.25, p_max=0.75, rho=0.85, s_levy_base=5e-4,
                      v_max_frac=0.15, use_sigmoid_p=True, k_sig=20.0, b_sig=0.5,
                      gamma_w=0.9, elitism_top_k=3, local_search_sigma=1e-3,
                      levy_trigger_patience=15, save_diag=False, diag_prefix="vasi2"):
    """
    VASI++ v2: adaptive switching + dynamic Levy + hybrid gbest + local search
    - levy_trigger_patience: number of iterations with small gbest improvement to increase levy probability
    - elitism_top_k: number of top pbest used to form ensemble gbest
    """
    # init
    x = np.random.uniform(lb, ub, (N, d))
    v = np.zeros((N, d))
    pbest = x.copy()
    pbest_fitness = obj_func(x)
    gbest_idx = np.argmin(pbest_fitness)
    gbest = pbest[gbest_idx].copy()
    gbest_fitness = pbest_fitness[gbest_idx]
    fitness_history = [gbest_fitness]

    span = np.abs(ub - lb)
    # if scalar or array handle
    if np.isscalar(span):
        v_max = v_max_frac * span
    else:
        v_max = v_max_frac * np.max(span)

    # diagnostic
    diag_rows = []
    # for adaptive p(t): track recent improvements
    recent_improvements = []

    for t in range(T):
        # --- compute diversity D(t) (normalized by dimension)
        D = np.mean([np.linalg.norm(x[i] - gbest) / (np.linalg.norm(gbest) + 1e-12) for i in range(N)])

        # --- inertia schedule (with gamma)
        w = w_max - (w_max - w_min) * ((t / T) ** gamma_w) * (1 - rho * D)

        # --- form ensemble gbest_e (hybrid global best)
        # use the average of top-k pbest to reduce noisy jumps
        top_k_idx = np.argsort(pbest_fitness)[:max(1, min(elitism_top_k, N))]
        ensemble_gbest = np.mean(pbest[top_k_idx], axis=0)
        # blend ensemble with classic gbest
        gbest_e = 0.6 * gbest + 0.4 * ensemble_gbest

        # --- compute p_raw based on diversity and recent improvement rate
        # improvement_rate: relative improvement of gbest over last iteration
        if len(fitness_history) >= 2:
            prev = fitness_history[-1]
            improvement = (prev - gbest_fitness) / (abs(prev) + 1e-12)
        else:
            improvement = 0.0
        recent_improvements.append(improvement)
        # keep rolling window
        if len(recent_improvements) > 20:
            recent_improvements.pop(0)
        avg_improv = np.mean(recent_improvements) if recent_improvements else 0.0

        # raw p: prefer exploitation when improvement high and diversity low
        p_raw = p_min + (p_max - p_min) * (0.5 * (1 - D) + 0.5 * (1 + np.tanh(5 * avg_improv)) / 2)
        # apply sigmoid stretch to avoid extremes
        if use_sigmoid_p:
            z = k_sig * (p_raw - b_sig)
            p_t = p_min + (p_max - p_min) * (1 / (1 + np.exp(-z)))
        else:
            p_t = np.clip(p_raw, p_min, p_max)

        # dynamic levy scale: decrease as improvement rate grows; increase if stuck
        # base scale small; scale factor depends on negative avg_improv (when stuck avg_improv ~ 0 or negative)
        stuck_factor = np.clip(-avg_improv, 0.0, 1.0)  # 0 if improving, up to 1 if stuck or worsening
        s_levy = s_levy_base * (1.0 + 5.0 * stuck_factor)  # up to ~6x when stuck

        # levy trigger probability increases when no improvement for patience window
        no_improv_count = sum(1 for v_ in recent_improvements if v_ <= 1e-12)
        levy_prob_bonus = min(0.5, no_improv_count / float(max(1, levy_trigger_patience)))
        # sigma_f for decision
        sigma_f = np.std(pbest_fitness)

        levy_count = 0
        # iterate particles
        for i in range(N):
            u_switch = np.random.uniform(0, 1)
            v_candidate = np.zeros(d)

            if u_switch < p_t:
                # PSO exploitation (use ensemble gbest_e instead of raw gbest)
                r1, r2, r3 = np.random.uniform(0, 1, 3)
                v_pso = w * v[i] + c1 * r1 * (pbest[i] - x[i]) + c2 * r2 * (gbest_e - x[i])
                v_candidate = v_pso + alpha * r3 * (gbest_e - x[i])
            else:
                # WSO exploration (use ensemble too)
                a_t = 2 * (1 - t / T)
                r = np.random.uniform(0, 1)
                A = 2 * a_t * r - a_t
                C = 2 * r
                if abs(A) < 1:
                    D_vec = np.abs(C * gbest_e - x[i])
                    x_encircle = gbest_e - A * D_vec
                    v_candidate = x_encircle - x[i]
                else:
                    k_idx = np.random.randint(0, N)
                    rand_whale = x[k_idx]
                    D_vec = np.abs(C * rand_whale - x[i])
                    x_search = rand_whale - A * D_vec
                    v_candidate = x_search - x[i]
                # spiral occasionally
                if np.random.uniform(0, 1) < 0.25:
                    l = np.random.uniform(-1, 1)
                    Dg = np.abs(gbest_e - x[i])
                    Dg = np.clip(Dg, 1e-12, np.inf)
                    x_spiral = Dg * np.exp(b * l) * np.cos(2 * np.pi * l) + gbest_e
                    v_candidate = 0.5 * (v_candidate + (x_spiral - x[i]))

            # clamp candidate velocity to avoid huge jumps
            norm_v = np.linalg.norm(v_candidate)
            if norm_v > 0:
                if norm_v > v_max:
                    v_candidate = v_candidate * (v_max / norm_v)

            # dynamic decision for Levy: use both candidate smallness and levy_prob_bonus
            levy_trigger = False
            if (np.linalg.norm(v_candidate) < 0.08 * v_max and sigma_f < 1e-4) or (np.random.uniform(0,1) < levy_prob_bonus * 0.2):
                # increased chance when stuck
                levy_trigger = True

            if levy_trigger:
                # Lévy flight (smaller scale)
                sigma_u = (gamma(1 + mu) * np.sin(np.pi * mu / 2) /
                          (gamma((1 + mu) / 2) * mu * 2**((mu - 1) / 2))) ** (1.0/mu)
                u = np.random.normal(0, sigma_u, d)
                v_norm = np.random.normal(0, 1, d)
                levy_step = u / (np.abs(v_norm) ** (1.0/mu) + 1e-12)
                x_new = x[i] + s_levy * levy_step * (gbest_e - x[i])
                levy_count += 1
            else:
                r5 = np.random.uniform(0, 1)
                x_new = x[i] + v_candidate + beta * r5 * (gbest_e - x[i])

            # boundary and evaluate
            x_new = np.clip(x_new, lb, ub)
            fitness_new = obj_func(x_new.reshape(1, -1))[0]

            # update v and x and pbest
            v[i] = v_candidate
            x[i] = x_new
            if fitness_new < pbest_fitness[i]:
                pbest[i] = x_new.copy()
                pbest_fitness[i] = fitness_new

        # local search: if no improvement in last few iters, apply small Gaussian mutation to top-elite
        if no_improv_count >= levy_trigger_patience:
            # apply to top 1 or top 2
            top_local = np.argsort(pbest_fitness)[:min(2, N)]
            for idx in top_local:
                mutation = np.random.normal(0, local_search_sigma, d) * (ub - lb)
                candidate = np.clip(pbest[idx] + mutation, lb, ub)
                f_cand = obj_func(candidate.reshape(1, -1))[0]
                if f_cand < pbest_fitness[idx]:
                    pbest[idx] = candidate.copy()
                    pbest_fitness[idx] = f_cand

        # update gbest and history
        current_best_idx = np.argmin(pbest_fitness)
        if pbest_fitness[current_best_idx] < gbest_fitness:
            gbest = pbest[current_best_idx].copy()
            gbest_fitness = pbest_fitness[current_best_idx]

        fitness_history.append(gbest_fitness)

        # diagnostics
        diag_rows.append({
            'iter': t, 'D': D, 'w': w, 'p_t': p_t, 'avg_improv': avg_improv,
            'sigma_f': sigma_f, 'gbest_fitness': gbest_fitness, 'levy_count': levy_count,
            'no_improv_count': no_improv_count
        })

    if save_diag:
        pd.DataFrame(diag_rows).to_csv(f'{diag_prefix}_diagnostics.csv', index=False)

    return gbest, gbest_fitness, fitness_history


# ---------------------------
# Comparison harness
# ---------------------------
def compare_algorithms(runs=30, N=50, T=500, d=30, lb=-5.12, ub=5.12):
    functions = {
        'Sphere': sphere,
        'Rastrigin': rastrigin,
        'Ackley': ackley
    }

    results = []

    for func_name, obj_func in functions.items():
        print(f"Testing on {func_name} function...")

        for algo_name, algo_func in [('PSO', pso), ('WSO', wso), ('VASI', vasi_plus_plus_v2)]:
            print(f"  Running {algo_name}...")
            best_fitnesses = []
            convergence_histories = []

            for r in range(runs):
                # seed per-run for reproducibility
                seed = 1000 + r
                random.seed(seed)
                np.random.seed(seed)

                if algo_name == 'VASI':
                    # enable diagnostics saving per run
                    prefix = f"{func_name}_{algo_name}_run{r}"
                    _, best_fitness, history = algo_func(
                        N, T, d, lb, ub, obj_func,
                        w_max=0.9, w_min=0.4, c1=1.5, c2=1.5,
                        alpha=0.1, beta=0.2, v_th=0.5, mu=1.5, b=1.0,
                        p_min=0.25, p_max=0.75, rho=0.8, s_levy_base=1e-3, # Corrected parameter name
                        v_max_frac=0.2, use_sigmoid_p=True, k_sig=10.0, b_sig=0.5,
                        gamma_w=1.0, save_diag=True, diag_prefix=prefix
                    )
                else:
                    _, best_fitness, history = algo_func(N, T, d, lb, ub, obj_func)

                best_fitnesses.append(best_fitness)
                convergence_histories.append(history)

            mean_best = np.mean(best_fitnesses)
            std_best = np.std(best_fitnesses)
            min_best = np.min(best_fitnesses)
            max_best = np.max(best_fitnesses)

            results.append([
                func_name, algo_name, min_best, max_best, mean_best, std_best
            ])

            # plot mean convergence
            max_len = max(len(h) for h in convergence_histories)
            padded = [np.pad(h, (0, max_len - len(h)), 'edge') for h in convergence_histories]
            mean_history = np.mean(padded, axis=0)

            plt.figure(figsize=(8, 4))
            plt.plot(mean_history, label=f'{algo_name}', linewidth=2)
            plt.title(f'Convergence Plot - {func_name} Function - {algo_name}')
            plt.xlabel('Iterations')
            plt.ylabel('Fitness (log scale)')
            plt.yscale('log')
            plt.legend()
            plt.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.savefig(f'{func_name}_{algo_name}_convergence.png', dpi=200)
            plt.close()

    # save results
    df = pd.DataFrame(results, columns=['Function', 'Algorithm', 'Best', 'Worst', 'Mean', 'Std'])
    df.to_csv('optimization_results_detailed.csv', index=False)
    summary = df.groupby(['Function', 'Algorithm']).agg({'Mean': ['mean', 'std'], 'Best': 'min', 'Worst': 'max'}).round(6)
    summary.to_csv('optimization_results_summary.csv')

    print("\n" + "="*50)
    print("COMPARISON COMPLETED SUCCESSFULLY!")
    print("="*50)
    print("\nResults saved to:")
    print("  - optimization_results_detailed.csv")
    print("  - optimization_results_summary.csv")
    print("  - Convergence plots for each function and algorithm")
    print("\nQUICK SUMMARY:")
    print(df.groupby(['Function', 'Algorithm'])['Mean'].mean().unstack().round(6))

# Run if main
if __name__ == "__main__":
    compare_algorithms(runs=10, N=30, T=300, d=30, lb=-5.12, ub=5.12)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import wilcoxon

# load detailed results (تأكد أن الملف يحتوي صفوف لكل run: Function, Algorithm, Best ...)
df = pd.read_csv('optimization_results_detailed.csv')

# إذا ملفك في شكل summary (one row per algo/function) أحتاج الملف الأصلي لكل run،
# وإلا استخدم الملف الذي حفظته من قبل (best_fitnesses لكل run).

# Group by function
functions = df['Function'].unique()
algos = df['Algorithm'].unique()

for func in functions:
    sub = df[df['Function'] == func]
    data = {alg: sub[sub['Algorithm'] == alg]['Best'].values for alg in algos}
    # boxplot
    plt.figure(figsize=(6,4))
    plt.boxplot([data.get(alg, np.array([np.nan])) for alg in algos], labels=algos, showmeans=True)
    plt.title(f'Boxplot of final best fitnesses - {func}')
    plt.ylabel('Fitness')
    plt.yscale('log')
    plt.grid(alpha=0.3)
    plt.savefig(f'boxplot_{func}.png', dpi=200, bbox_inches='tight')
    plt.close()

    # Wilcoxon tests (paired) - check lengths
    # We assume same number of runs and aligned seeds; if not, use Mann-Whitney U.
    if all(len(data.get(alg, [])) == len(data.get('VASI', [])) for alg in ['PSO','WSO']):
        print(f'\nFunction: {func}')
        for other in ['PSO','WSO']:
            if other in algos:
                stat, p = wilcoxon(data['VASI'], data[other])
                print(f'  VASI vs {other}: Wilcoxon stat={stat:.3f}, p={p:.4e}')
    else:
        print(f'\nFunction: {func} - unequal run counts; use unpaired test (Mann-Whitney).')

import itertools
import numpy as np
import pandas as pd
from tqdm import tqdm

# ranges to try
v_max_fracs = [0.12, 0.15, 0.2, 0.25]
s_levy_bases = [5e-4, 2e-3, 5e-3]
elitism_ks = [1, 2, 3]
p_pairs = [(0.15,0.6), (0.2,0.7), (0.25,0.75)]

results = []
runs_per_setting = 10  # start small

for v_max_frac, s_levy_base, elitism_k, (p_min, p_max) in tqdm(list(itertools.product(v_max_fracs, s_levy_bases, elitism_ks, p_pairs))):
    bests = []
    for run in range(runs_per_setting):
        seed = 2000 + run
        np.random.seed(seed)
        random.seed(seed)
        _, best_f, _ = vasi_plus_plus_v2(
            N=30, T=300, d=30, lb=-5.12, ub=5.12,
            obj_func=rastrigin,
            v_max_frac=v_max_frac,
            s_levy_base=s_levy_base,
            elitism_top_k=elitism_k,
            p_min=p_min, p_max=p_max,
            save_diag=False
        )
        bests.append(best_f)
    results.append({
        'v_max_frac': v_max_frac,
        's_levy_base': s_levy_base,
        'elitism_k': elitism_k,
        'p_min': p_min,
        'p_max': p_max,
        'mean_best': np.mean(bests),
        'std_best': np.std(bests),
        'min_best': np.min(bests)
    })

pd.DataFrame(results).sort_values('mean_best').to_csv('param_sweep_rastrigin.csv', index=False)
print('Grid search done, saved param_sweep_rastrigin.csv')

import matplotlib.pyplot as plt
import numpy as np

# Data for comparison
functions = ["Sphere", "Rastrigin", "Ackley"]
algorithms = ["PSO", "VASI", "WSO"]
values = np.array([
    [3.61, 0.000028, 6.2e-10],   # Sphere
    [212.34, 0.022, 1.35e-08],   # Rastrigin
    [9.58, 0.00094, 8.6e-09]     # Ackley
])

# Plot setup
x = np.arange(len(functions))
width = 0.25

plt.figure(figsize=(10,6))
for i, algo in enumerate(algorithms):
    plt.bar(x + (i - 1)*width, values[:, i], width=width, label=algo)

plt.yscale('log')
plt.xticks(x, functions, fontsize=12)
plt.ylabel('Objective Function Value (log scale)', fontsize=12)
plt.title('Comparison of PSO, VASI, and WSO on Benchmark Functions', fontsize=14, fontweight='bold')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

