# -*- coding: utf-8 -*-
"""2 VASI_Hybrid_model ready_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFne265zldEgI3AaAAdK86I7DoJzc2yC
"""

from google.colab import drive
drive.mount('/content/drive')

# -------------------------
# Paths & normalizer
# -------------------------
DATASET_PATH = '/content/drive/MyDrive/breakhis_dataset/BreaKHis_v1/histology_slides/breast'

class_names = ['benign', 'malignant']

import os
import cv2
import random
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import torch.optim as optim
from tqdm import tqdm
from scipy.special import gamma
import matplotlib.pyplot as plt # Import matplotlib for plotting



# -------------------------
# Model definitions (modified to accept qtn_outdim, classifier_hidden, dropout)
# -------------------------
class AttentionFusion(nn.Module):
    def __init__(self, in_dim=256, num_features=4):
        super(AttentionFusion, self).__init__()
        self.proj = nn.Linear(in_dim, in_dim)
        self.attn = nn.Linear(in_dim, 1)
        self.num_features = num_features
    def forward(self, features):
        stacked = torch.stack(features, dim=1)  # [B, num_features, in_dim]
        proj = torch.tanh(self.proj(stacked))
        attn_scores = self.attn(proj)
        attn_weights = F.softmax(attn_scores, dim=1)
        fused = torch.sum(attn_weights * stacked, dim=1)
        return fused

class MFF_CNN(nn.Module):
    def __init__(self, pretrained=True):
        super(MFF_CNN, self).__init__()
        resnet = models.resnet50(weights='DEFAULT' if pretrained else None)
        self.layer0 = nn.Sequential(resnet.conv1, resnet.bn1, resnet.relu, resnet.maxpool)
        self.layer1 = resnet.layer1
        self.layer2 = resnet.layer2
        self.layer3 = resnet.layer3
        self.layer4 = resnet.layer4
        self.proj1 = nn.Conv2d(256, 256, kernel_size=1)
        self.proj2 = nn.Conv2d(512, 256, kernel_size=1)
        self.proj3 = nn.Conv2d(1024, 256, kernel_size=1)
        self.proj4 = nn.Conv2d(2048, 256, kernel_size=1)
        self.global_pool = nn.AdaptiveAvgPool2d((1,1))
        self.attn_fusion = AttentionFusion(in_dim=256, num_features=4)

    def forward(self, x):
        x0 = self.layer0(x)
        x1 = self.layer1(x0)
        x2 = self.layer2(x1)
        x3 = self.layer3(x2)
        x4 = self.layer4(x3)
        f1 = self.global_pool(self.proj1(x1)).flatten(1)
        f2 = self.global_pool(self.proj2(x2)).flatten(1)
        f3 = self.global_pool(self.proj3(x3)).flatten(1)
        f4 = self.global_pool(self.proj4(x4)).flatten(1)
        fused_features = self.attn_fusion([f1, f2, f3, f4])
        return fused_features

class QTN_Layer(nn.Module):
    def __init__(self, input_dim=256, output_dim=128):
        super(QTN_Layer, self).__init__()
        self.compress = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Linear(512, output_dim),
            nn.ReLU()
        )
    def forward(self, x):
        return self.compress(x)

class MFF_HistoNet(nn.Module):
    def __init__(self, num_classes=2, qtn_outdim=128, classifier_hidden=64, dropout=0.4, pretrained_backbone=False):
        super(MFF_HistoNet, self).__init__()
        self.cnn_backbone = MFF_CNN(pretrained=pretrained_backbone)
        self.qtn_layer = QTN_Layer(input_dim=256, output_dim=int(qtn_outdim))
        self.classifier = nn.Sequential(
            nn.Linear(int(qtn_outdim), int(classifier_hidden)),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(int(classifier_hidden), num_classes)
        )
    def forward(self, image):
        cnn_feat = self.cnn_backbone(image)
        qtn_feat = self.qtn_layer(cnn_feat)
        output = self.classifier(qtn_feat)
        return output

# -------------------------
# VASI++ optimizer (KEPT as-is except initial fitness handling robust)
# -------------------------
def vasi_plus_plus_v2(N, T, d, lb, ub, obj_func,
                      w_max=0.9, w_min=0.4, c1=1.5, c2=1.5,
                      alpha=0.08, beta=0.15, v_th=0.5, mu=1.5, b=1.0,
                      p_min=0.25, p_max=0.75, rho=0.85, s_levy_base=5e-4,
                      v_max_frac=0.15, use_sigmoid_p=True, k_sig=20.0, b_sig=0.5,
                      gamma_w=0.9, elitism_top_k=3, local_search_sigma=1e-3,
                      levy_trigger_patience=15, save_diag=False, diag_prefix="vasi2"):
    x = np.random.uniform(lb, ub, (N, d))
    v = np.zeros((N, d))
    pbest = x.copy()

    # robust initial evaluation: allow obj_func to accept batch or single
    try:
        # if obj_func can take full batch and return array-like:
        pbest_fitness = np.asarray(obj_func(x))
        if pbest_fitness.shape[0] != N:
            raise ValueError
    except Exception:
        # fallback: evaluate per-particle
        pbest_fitness = np.zeros(N)
        for i in range(N):
            val = obj_func(x[i].reshape(1, -1))
            # obj_func may return scalar or array
            pbest_fitness[i] = float(np.asarray(val).ravel()[0])

    gbest_idx = np.argmin(pbest_fitness)
    gbest = pbest[gbest_idx].copy()
    gbest_fitness = pbest_fitness[gbest_idx]
    fitness_history = [gbest_fitness]

    span = np.abs(ub - lb)
    v_max = v_max_frac * (span if np.isscalar(span) else np.max(span))

    diag_rows = []
    recent_improvements = []

    for t in range(T):
        D = np.mean([np.linalg.norm(x[i] - gbest) / (np.linalg.norm(gbest) + 1e-12) for i in range(N)])
        w = w_max - (w_max - w_min) * ((t / T) ** gamma_w) * (1 - rho * D)

        top_k_idx = np.argsort(pbest_fitness)[:max(1, min(elitism_top_k, N))]
        ensemble_gbest = np.mean(pbest[top_k_idx], axis=0)
        gbest_e = 0.6 * gbest + 0.4 * ensemble_gbest

        if len(fitness_history) >= 2:
            prev = fitness_history[-1]
            improvement = (prev - gbest_fitness) / (abs(prev) + 1e-12)
        else:
            improvement = 0.0
        recent_improvements.append(improvement)
        if len(recent_improvements) > 20:
            recent_improvements.pop(0)
        avg_improv = np.mean(recent_improvements) if recent_improvements else 0.0

        p_raw = p_min + (p_max - p_min) * (0.5 * (1 - D) + 0.5 * (1 + np.tanh(5 * avg_improv)) / 2)
        if use_sigmoid_p:
            z = k_sig * (p_raw - b_sig)
            p_t = p_min + (p_max - p_min) * (1 / (1 + np.exp(-z)))
        else:
            p_t = np.clip(p_raw, p_min, p_max)

        stuck_factor = np.clip(-avg_improv, 0.0, 1.0)
        s_levy = s_levy_base * (1.0 + 5.0 * stuck_factor)
        no_improv_count = sum(1 for v_ in recent_improvements if v_ <= 1e-12)
        levy_prob_bonus = min(0.5, no_improv_count / float(max(1, levy_trigger_patience)))
        sigma_f = np.std(pbest_fitness)

        levy_count = 0
        for i in range(N):
            u_switch = np.random.uniform(0, 1)
            v_candidate = np.zeros(d)

            if u_switch < p_t:
                r1, r2, r3 = np.random.uniform(0, 1, 3)
                v_pso = w * v[i] + c1 * r1 * (pbest[i] - x[i]) + c2 * r2 * (gbest_e - x[i])
                v_candidate = v_pso + alpha * r3 * (gbest_e - x[i])
            else:
                a_t = 2 * (1 - t / T)
                r = np.random.uniform(0, 1)
                A = 2 * a_t * r - a_t
                C = 2 * r
                if abs(A) < 1:
                    D_vec = np.abs(C * gbest_e - x[i])
                    x_encircle = gbest_e - A * D_vec
                    v_candidate = x_encircle - x[i]
                else:
                    k_idx = np.random.randint(0, N)
                    rand_whale = x[k_idx]
                    D_vec = np.abs(C * rand_whale - x[i])
                    x_search = rand_whale - A * D_vec
                    v_candidate = x_search - x[i]
                if np.random.uniform(0, 1) < 0.25:
                    l = np.random.uniform(-1, 1)
                    Dg = np.abs(gbest_e - x[i])
                    Dg = np.clip(Dg, 1e-12, np.inf)
                    x_spiral = Dg * np.exp(b * l) * np.cos(2 * np.pi * l) + gbest_e
                    v_candidate = 0.5 * (v_candidate + (x_spiral - x[i]))

            norm_v = np.linalg.norm(v_candidate)
            if norm_v > 0 and norm_v > v_max:
                v_candidate = v_candidate * (v_max / norm_v)

            levy_trigger = False
            if (np.linalg.norm(v_candidate) < 0.08 * v_max and sigma_f < 1e-4) or (np.random.uniform(0,1) < levy_prob_bonus * 0.2):
                levy_trigger = True

            if levy_trigger:
                sigma_u = (gamma(1 + mu) * np.sin(np.pi * mu / 2) /
                          (gamma((1 + mu) / 2) * mu * 2**((mu - 1) / 2))) ** (1.0/mu)
                u = np.random.normal(0, sigma_u, d)
                v_norm = np.random.normal(0, 1, d)
                levy_step = u / (np.abs(v_norm) ** (1.0/mu) + 1e-12)
                x_new = x[i] + s_levy * levy_step * (gbest_e - x[i])
                levy_count += 1
            else:
                r5 = np.random.uniform(0, 1)
                x_new = x[i] + v_candidate + beta * r5 * (gbest_e - x[i])

            x_new = np.clip(x_new, lb, ub)

            # evaluate: obj_func should accept single-sample shaped (1,d) and return scalar or array
            try:
                fitness_new_arr = np.asarray(obj_func(x_new.reshape(1, -1)))
                fitness_new = float(fitness_new_arr.ravel()[0])
            except Exception:
                fitness_new = float(np.asarray(obj_func(x_new))[0])

            v[i] = v_candidate
            x[i] = x_new
            if fitness_new < pbest_fitness[i]:
                pbest[i] = x_new.copy()
                pbest_fitness[i] = fitness_new

        if no_improv_count >= levy_trigger_patience:
            top_local = np.argsort(pbest_fitness)[:min(2, N)]
            for idx in top_local:
                mutation = np.random.normal(0, local_search_sigma, d) * (ub - lb)
                candidate = np.clip(pbest[idx] + mutation, lb, ub)
                f_cand_arr = np.asarray(obj_func(candidate.reshape(1, -1)))
                f_cand = float(f_cand_arr.ravel()[0])
                if f_cand < pbest_fitness[idx]:
                    pbest[idx] = candidate.copy()
                    pbest_fitness[idx] = f_cand

        current_best_idx = np.argmin(pbest_fitness)
        if pbest_fitness[current_best_idx] < gbest_fitness:
            gbest = pbest[current_best_idx].copy()
            gbest_fitness = pbest_fitness[current_best_idx]

        fitness_history.append(gbest_fitness)
        diag_rows.append({
            'iter': t, 'D': D, 'w': w, 'p_t': p_t, 'avg_improv': avg_improv,
            'sigma_f': sigma_f, 'gbest_fitness': gbest_fitness, 'levy_count': levy_count,
            'no_improv_count': no_improv_count
        })

    if save_diag:
        # Use diag_rows for saving diagnostics
        pd.DataFrame(diag_rows).to_csv(f'{diag_prefix}_diagnostics.csv', index=False)


    return gbest, gbest_fitness, fitness_history # Return fitness_history

# -------------------------
# evaluate_model: accepts single or batch (N,d)
# -------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
def evaluate_single(hvec, max_batches=64, pretrained_backbone=False):
    # hvec is 1D numpy array or list: [lr, dropout, qtn_outdim, hidden_dim]
    lr = float(hvec[0])
    dropout = float(hvec[1])
    qtn_outdim = max(8, int(round(hvec[2])))
    hidden_dim = max(8, int(round(hvec[3])))

    # instantiate small model (pretrained_backbone default False to speed up)
    model = MFF_HistoNet(num_classes=len(class_names),
                        qtn_outdim=qtn_outdim,
                        classifier_hidden=hidden_dim,
                        dropout=dropout,
                        pretrained_backbone=pretrained_backbone).to(device)

    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    model.train()
    batch_count = 0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        batch_count += 1
        if batch_count >= max_batches:
            break

    # evaluate on val_loader
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in val_loader: # Use val_loader for evaluation
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    acc = (correct / total) if total > 0 else 0.0
    return 1.0 - acc

def evaluate_model(hypervector):
    arr = np.asarray(hypervector)
    if arr.ndim == 2:
        out = []
        for r in arr:
            out.append(evaluate_single(r, max_batches=64, pretrained_backbone=False))
        return np.array(out)
    else:
        return evaluate_single(arr, max_batches=64, pretrained_backbone=False)



# -------------------------
# Hyperparameter optimization harness
# -------------------------
def optimize_hyperparams(save_dir="./best_vasi_model"):
    os.makedirs(save_dir, exist_ok=True)
    lb = np.array([1e-5, 0.1, 64, 32])
    ub = np.array([1e-3, 0.6, 256, 256])
    N, T, d = 8, 12, 4  # reduce for speed during development
    # Capture fitness_history from VASI++
    best_vec, best_fit, vasi_history = vasi_plus_plus_v2(
        N, T, d, lb, ub,
        obj_func=evaluate_model,
        save_diag=True,
        diag_prefix=os.path.join(save_dir, "vasi_log")
    )
    print("Best hyperparameters:", best_vec, "(best val acc):", 1 - best_fit)

    # Plot VASI++ convergence
    # plot_convergence(vasi_history)


    # retrain final model with found hyperparameters fully (longer)
    lr, dropout, qtn_outdim, hidden_dim = best_vec
    model = MFF_HistoNet(num_classes=len(class_names),
                         qtn_outdim=int(round(qtn_outdim)),
                         classifier_hidden=int(round(hidden_dim)),
                         dropout=float(dropout),
                         pretrained_backbone=True).to(device)
    optimizer = optim.Adam(model.parameters(), lr=float(lr))
    criterion = nn.CrossEntropyLoss()

    print("Retraining final model for 10 epochs on full train set...")

    # Track loss and accuracy during final training
    train_losses = []
    train_accuracies = []
    val_losses = []
    val_accuracies = []

    for epoch in range(10):
        # Training loop
        model.train()
        total_train_loss = 0
        correct_train, total_train = 0, 0
        for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{10} (Train)"):
            images = images.to(device)
            labels = labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_train_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total_train += labels.size(0)
            correct_train += (predicted == labels).sum().item()

        avg_train_loss = total_train_loss / len(train_loader)
        train_acc = correct_train / total_train
        train_losses.append(avg_train_loss)
        train_accuracies.append(train_acc)

        # Validation loop
        model.eval()
        total_val_loss = 0
        correct_val, total_val = 0, 0
        with torch.no_grad():
            for images, labels in tqdm(val_loader, desc=f"Epoch {epoch+1}/{10} (Val)"): # Evaluate on val_loader
                images = images.to(device)
                labels = labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)
                total_val_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                total_val += labels.size(0)
                correct_val += (predicted == labels).sum().item()

        avg_val_loss = total_val_loss / len(val_loader)
        val_acc = correct_val / total_val
        val_losses.append(avg_val_loss)
        val_accuracies.append(val_acc)

        print(f"Epoch {epoch+1}: Train Loss: {avg_train_loss:.4f}, Train Acc: {train_acc:.4f}, Val Loss: {avg_val_loss:.4f}, Val Acc: {val_acc:.4f}")


    # Plot training/validation curves
    #plot_metrics(train_losses, train_accuracies, val_losses, val_accuracies)


    model_path = os.path.join(save_dir, "best_mff_vasi_model.pt")
    torch.save(model.state_dict(), model_path)
    print(f"Saved final model to: {model_path}")
    return model, best_vec

# run optimization
if __name__ == "__main__":
    best_model, best_params = optimize_hyperparams(save_dir="./VASI_best_model")

