# -*- coding: utf-8 -*-
"""3 second_data_main_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192nY10sBupAW0ppy2JW2u7B5gGlt67b1
"""

from google.colab import drive
drive.mount('/content/drive')

import os

"""First, we'll download the dataset zip file from Kaggle using `curl`."""

!curl -L -o /content/pediatric-pneumonia-chest-xray.zip \
  https://www.kaggle.com/api/v1/datasets/download/andrewmvd/pediatric-pneumonia-chest-xray

"""Next, we'll unzip the downloaded file."""

!unzip -q /content/pediatric-pneumonia-chest-xray.zip -d /content/pediatric-pneumonia-chest-xray

drive_path = '/content/drive/MyDrive/pediatric-pneumonia-xray-dataset'

if not os.path.exists(drive_path):
    os.makedirs(drive_path)
    print(f"Created directory: {drive_path}")
else:
    print(f"Directory already exists: {drive_path}")

# Move the unzipped contents to Google Drive
!mv /content/pediatric-pneumonia-chest-xray/* "{drive_path}"

print(f"Dataset moved to: {drive_path}")

"""Now, let's prepare the data for splitting. We need to identify the different classes and gather all image paths."""

import glob
from sklearn.model_selection import train_test_split
import shutil

data_dir = drive_path

# Let's see what's inside the main data directory
print(f"Contents of {data_dir}:")
print(os.listdir(data_dir))

# Assuming the dataset structure is like: pediatric-pneumonia-xray-dataset/train/NORMAL, pediatric-pneumonia-xray-dataset/train/PNEUMONIA etc.
# We need to find the actual image directories within the main dataset folder.

# Common subdirectories for image datasets are 'train', 'test', 'val'
# Let's check for these, or directly look for 'NORMAL'/'PNEUMONIA' if they are top-level

image_paths = []
labels = []

# List all subdirectories to find where the actual image classes are
# Adjust this logic based on the actual output of os.listdir(data_dir)
# A common structure is data_dir/class_name/image.png

# For this dataset, the structure is typically data_dir/[train/val/test]/[NORMAL/PNEUMONIA]/
# Let's assume the unzipped content is directly inside pediatric-pneumonia-chest-xray
# And that it contains 'train', 'test', 'val' folders

# Let's find all image paths from the main data_dir that represent classes
# We'll traverse the structure to get image paths and their labels.

for root, dirs, files in os.walk(data_dir):
    for dir_name in dirs:
        # Check if dir_name is a potential class label (e.g., 'NORMAL', 'PNEUMONIA')
        # This might need refinement based on the exact structure of the unzipped data
        if dir_name.lower() in ['normal', 'pneumonia']:
            class_path = os.path.join(root, dir_name)
            for img_path in glob.glob(os.path.join(class_path, '*.jpeg')):
                image_paths.append(img_path)
                labels.append(dir_name)
            for img_path in glob.glob(os.path.join(class_path, '*.png')):
                image_paths.append(img_path)
                labels.append(dir_name)

print(f"Found {len(image_paths)} images.")
print(f"Unique labels found: {set(labels)}")

"""Now, we will split the collected image paths into training and testing sets with a `test_size` of 0.3."""

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(image_paths, labels, test_size=0.3, random_state=42, stratify=labels)

print(f"Number of training images: {len(X_train)}")
print(f"Number of testing images: {len(X_test)}")

# Verify stratification (optional)
from collections import Counter
print("Training set distribution:", Counter(y_train))
print("Testing set distribution:", Counter(y_test))

"""Finally, we will create new directories in Google Drive for the training and testing datasets and copy the respective images into them."""

base_output_dir = '/content/drive/MyDrive/pediatric-pneumonia-xray-split'

# Create train and test directories
train_output_dir = os.path.join(base_output_dir, 'train')
test_output_dir = os.path.join(base_output_dir, 'test')

for path in [train_output_dir, test_output_dir]:
    os.makedirs(path, exist_ok=True)
    os.makedirs(os.path.join(path, 'NORMAL'), exist_ok=True)
    os.makedirs(os.path.join(path, 'PNEUMONIA'), exist_ok=True)

print(f"Created output directories: {train_output_dir} and {test_output_dir}")

# Function to copy files
def copy_files(image_list, label_list, destination_base):
    for i, img_path in enumerate(image_list):
        label = label_list[i]
        filename = os.path.basename(img_path)
        dest_path = os.path.join(destination_base, label, filename)
        shutil.copy(img_path, dest_path)

print("Copying training images...")
copy_files(X_train, y_train, train_output_dir)
print("Copying testing images...")
copy_files(X_test, y_test, test_output_dir)

print("Data splitting and copying complete!")
print(f"Train data saved to: {train_output_dir}")
print(f"Test data saved to: {test_output_dir}")

"""### Re-initializing Data Loaders, Model, and Training Setup

Since the runtime was changed, the Python kernel's state has been reset. We need to re-execute the code cells that define our image transformations, create our `DataLoader`s, define the PyTorch model architecture, and set up the optimizer and loss function. I will re-create these steps below.
"""

import torch
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
import os
import torch.nn as nn
import torchvision.models as models
from tqdm import tqdm
from sklearn.metrics import accuracy_score
import numpy as np

# Define image transformations
train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomRotation(10),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Define the paths to split datasets
base_output_dir = '/content/drive/MyDrive/pediatric-pneumonia-xray-split'
train_output_dir = os.path.join(base_output_dir, 'train')
test_output_dir = os.path.join(base_output_dir, 'test')

# Create Dataset objects
train_dataset = ImageFolder(root=train_output_dir, transform=train_transforms)
test_dataset = ImageFolder(root=test_output_dir, transform=test_transforms)

# Determine class names and number of classes
class_names = train_dataset.classes
num_classes = len(class_names)
print(f"Class names: {class_names}")
print(f"Number of classes: {num_classes}")

# Create DataLoader objects
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0)

print(f"Training DataLoader created with {len(train_loader)} batches.")
print(f"Testing DataLoader created with {len(test_loader)} batches.")

# ✅ Base CNN Backbone (ResNet50)
class MFF_CNN(nn.Module):
    def __init__(self, pretrained=True):
        super(MFF_CNN, self).__init__()
        resnet = models.resnet50(weights='DEFAULT' if pretrained else None)

        self.layer0 = nn.Sequential(resnet.conv1, resnet.bn1, resnet.relu, resnet.maxpool)
        self.layer1 = resnet.layer1
        self.layer2 = resnet.layer2
        self.layer3 = resnet.layer3
        self.layer4 = resnet.layer4

        self.proj1 = nn.Conv2d(256, 256, kernel_size=1)
        self.proj2 = nn.Conv2d(512, 256, kernel_size=1)
        self.proj3 = nn.Conv2d(1024, 256, kernel_size=1)
        self.proj4 = nn.Conv2d(2048, 256, kernel_size=1)

        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

    def forward(self, x):
        x0 = self.layer0(x)
        x1 = self.layer1(x0)
        x2 = self.layer2(x1)
        x3 = self.layer3(x2)
        x4 = self.layer4(x3)

        f1 = self.global_pool(self.proj1(x1)).flatten(1)
        f2 = self.global_pool(self.proj2(x2)).flatten(1)
        f3 = self.global_pool(self.proj3(x3)).flatten(1)
        f4 = self.global_pool(self.proj4(x4)).flatten(1)

        fused_features = torch.cat([f1, f2, f3, f4], dim=1)
        return fused_features

# ✅ Simple QTN-like Feature Compression (linear projection)
class QTN_Layer(nn.Module):
    def __init__(self, input_dim=1024, output_dim=128):
        super(QTN_Layer, self).__init__()
        self.compress = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Linear(512, output_dim),
            nn.ReLU()
        )

    def forward(self, x):
        return self.compress(x)

# ✅ Main Model Combining CNN + QTN (Texture Features Removed)
class MFF_HistoNet(nn.Module):
    def __init__(self, num_classes=2):
        super(MFF_HistoNet, self).__init__()
        self.cnn_backbone = MFF_CNN()
        self.qtn_layer = QTN_Layer(input_dim=1024, output_dim=128)
        self.classifier = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(64, num_classes)
        )

    def forward(self, image):
        cnn_feat = self.cnn_backbone(image)
        qtn_feat = self.qtn_layer(cnn_feat)
        output = self.classifier(qtn_feat)
        return output

print("Model architecture defined: MFF_CNN, QTN_Layer, MFF_HistoNet")

"""Now, we will instantiate the model, loss function, and optimizer."""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_mff = MFF_HistoNet(num_classes=num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_mff.parameters(), lr=1e-4)

print("Modified MFF_HistoNet model instantiated.")
print(f"Using device: {device}")
print(f"Number of classes for model: {num_classes}")

"""Next, we'll re-define the training and validation epoch functions."""

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_labels = []
    all_preds = []

    for inputs, labels in tqdm(dataloader, desc="Training"):
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)

        _, predicted = torch.max(outputs.data, 1)
        all_labels.extend(labels.cpu().numpy())
        all_preds.extend(predicted.cpu().numpy())

    epoch_loss = running_loss / len(dataloader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc

def validate_epoch(model, dataloader, criterion, device):
    model.eval()
    running_loss = 0.0
    all_labels = []
    all_preds = []

    with torch.no_grad():
        for inputs, labels in tqdm(dataloader, desc="Validation"):
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * inputs.size(0)

            _, predicted = torch.max(outputs.data, 1)
            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(predicted.cpu().numpy())

    epoch_loss = running_loss / len(dataloader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc, all_labels, all_preds

print("Training and validation epoch functions defined.")

"""Finally, we can start the training loop."""

num_epochs = 5
best_acc = 0.0

train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []

print(f"Starting training for {num_epochs} epochs...")

for epoch in range(num_epochs):
    train_loss, train_acc = train_epoch(model_mff, train_loader, criterion, optimizer, device)
    val_loss, val_acc, _, _ = validate_epoch(model_mff, test_loader, criterion, device)

    train_losses.append(train_loss)
    train_accuracies.append(train_acc)
    val_losses.append(val_loss)
    val_accuracies.append(val_acc)

    print(f'Epoch {epoch+1}/{num_epochs} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f} - Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}')

    if val_acc > best_acc:
        best_acc = val_acc
        torch.save(model_mff.state_dict(), 'best_mff_model.pth')
        print(f"Saved best model with validation accuracy: {best_acc:.4f}")

print("Training complete!")

import matplotlib.pyplot as plt


# Plot training and validation loss (Separate Figure)
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(train_losses) + 1), train_losses, marker='o', linestyle='-', label='Train Loss', linewidth=2)
plt.plot(range(1, len(val_losses) + 1), val_losses, marker='s', linestyle='-', label='Test Loss', linewidth=2)
plt.xlabel('Epoch', weight='bold', fontsize=12)
plt.ylabel('Loss', weight='bold', fontsize=12)
plt.title('Training and Test Loss per Epoch for HistoFusion model', weight='bold', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.xticks(range(1, 6))
plt.tight_layout()
plt.show()

# Plot training and validation accuracy (Separate Figure)
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(train_accuracies) + 1), train_accuracies, marker='o', linestyle='-', label='Train Accuracy', linewidth=2)
plt.plot(range(1, len(val_accuracies) + 1), val_accuracies, marker='s', linestyle='-', label='Test Accuracy', linewidth=2)
plt.xlabel('Epoch', weight='bold', fontsize=12)
plt.ylabel('Accuracy (%)', weight='bold', fontsize=12)
plt.title('Training and Test Accuracy per Epoch for HistoFusion model', weight='bold', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.ylim(80, 100)  # Set y-axis limits to better visualize the accuracy range
plt.xticks(range(1, 6))
plt.tight_layout()
plt.show()

import torch
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set the model to evaluation mode
model_mff.eval()

all_labels = []
all_predictions = []
all_probabilities = [] # List to store probabilities

# Disable gradient calculation for evaluation
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc="Evaluating Model"): # Modified line: removed img_paths
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model_mff(inputs)
        _, predicted = torch.max(outputs.data, 1)

        # Get probabilities (apply softmax if needed, but CrossEntropyLoss includes softmax internally)
        # For binary classification with CrossEntropyLoss, the output is typically logits.
        # We can use softmax to get probabilities, or just use the logits of the positive class.
        # Let's use softmax to be more explicit.
        probabilities = torch.softmax(outputs, dim=1)[:, 1] # Probability of the positive class (assuming PNEUMONIA is class 1)


        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())
        all_probabilities.extend(probabilities.cpu().numpy()) # Store probabilities

print("Model evaluation complete. Calculating metrics...")

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Calculate ROC curve and AUC
fpr, tpr, thresholds = roc_curve(all_labels, all_probabilities)
roc_auc = auc(fpr, tpr)

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate',weight='bold')
plt.ylabel('True Positive Rate',weight='bold')
plt.title('Receiver Operating Characteristic (ROC) Curve for HistoFusion model',weight='bold')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print(f"AUC: {roc_auc:.4f}")

from sklearn.metrics import precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt

# Calculate Precision-Recall curve and Average Precision Score
precision, recall, _ = precision_recall_curve(all_labels, all_probabilities)
average_precision = average_precision_score(all_labels, all_probabilities)

# Plot Precision-Recall curve
plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='darkorange', lw=2, label='Precision-Recall curve (AP = %0.2f)' % average_precision)
plt.xlabel('Recall',weight='bold')
plt.ylabel('Precision',weight='bold')
plt.title('Precision-Recall Curve for HistoFusion model',weight='bold')
plt.legend(loc="lower left")
plt.grid(True)
plt.show()

print(f"Average Precision (AP): {average_precision:.4f}")

import torch
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Convert lists to numpy arrays
all_labels = np.array(all_labels)
all_predictions = np.array(all_predictions)

# Generate Confusion Matrix
conf_matrix = confusion_matrix(all_labels, all_predictions)
total_samples = conf_matrix.sum()

print("\nConfusion Matrix:")
print(conf_matrix)

# Calculate percentages (row-wise)
conf_matrix_percent = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]

# Calculate percentage of total samples
conf_matrix_total_percent = conf_matrix / total_samples

# Create enhanced annotations with color control
class_names = ['benign', 'malignant']

# Prepare annotations with white color for TP cell
annotations = [
    [f"TN: {conf_matrix[0,0]}\n({conf_matrix_percent[0,0]:.1%})\n{conf_matrix_total_percent[0,0]:.1%}",
     f"FP: {conf_matrix[0,1]}\n({conf_matrix_percent[0,1]:.1%})\n{conf_matrix_total_percent[0,1]:.1%}"],
    [f"FN: {conf_matrix[1,0]}\n({conf_matrix_percent[1,0]:.1%})\n{conf_matrix_total_percent[1,0]:.1%}",
     f"TP: {conf_matrix[1,1]}\n({conf_matrix_percent[1,1]:.1%})\n{conf_matrix_total_percent[1,1]:.1%}"]
]

# Create a mask for TP cell to apply white color
annot_colors = [["black", "black"], ["black", "white"]]  # Colors for [TN, FP], [FN, TP]

# Plot Confusion Matrix with larger text
plt.rcParams.update({'font.size': 14})
fig, ax = plt.subplots(figsize=(10, 8))

# Create heatmap with custom text colors
heatmap = sns.heatmap(
    conf_matrix,
    annot=annotations,
    fmt='',
    cmap='Blues',
    annot_kws={"size": 16, "weight": "bold"},
    xticklabels=class_names,
    yticklabels=class_names,
    ax=ax,
    linewidths=0.5,
    linecolor='gray',
    cbar=True,
    square=True
)

# Manually set text colors after creating the heatmap
for i, text_row in enumerate(heatmap.texts):
    # The texts are ordered by row then column
    if i == 3:  # TP cell (last cell)
        text_row.set_color("white")
    else:
        text_row.set_color("black")

# Customize colorbar
cbar = heatmap.collections[0].colorbar
cbar.ax.tick_params(labelsize=14)
cbar.set_label('Number of Samples', fontsize=16, weight='bold')

# Axis labels with larger font
ax.set_xlabel('Predicted Label', fontsize=16, weight='bold')
ax.set_ylabel('True Label', fontsize=16, weight='bold')
ax.set_title('Confusion Matrix for HistoFusion model', fontsize=18, weight='bold')

# Customize tick labels
ax.set_xticklabels(class_names, fontsize=14, weight='bold')
ax.set_yticklabels(class_names, fontsize=14, weight='bold', rotation=0)

# Adjust layout
plt.tight_layout()

# Display the figure
plt.show()

# Generate Classification Report
print("\nClassification Report:")
print(classification_report(all_labels, all_predictions, target_names=class_names))

from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Calculate Precision, Recall, and F1-Score (for the positive class, which is 'malignant' based on class_names and labels_encoded)
# Assuming 'malignant' is the positive class (label 1)
precision = precision_score(all_labels, all_predictions, pos_label=1)
recall = recall_score(all_labels, all_predictions, pos_label=1)
f1 = f1_score(all_labels, all_predictions, pos_label=1)

# Calculate Cohen's Kappa Score
kappa = cohen_kappa_score(all_labels, all_predictions)

print(f"Precision (PPV) for Malignant: {precision:.4f}")
print(f"Recall (Sensitivity) for Malignant: {recall:.4f}")
print(f"F1-Score for Malignant: {f1:.4f}")
print(f"Cohen's Kappa Score: {kappa:.4f}")

import numpy as np
from scipy.stats import pearsonr, chi2_contingency, f_oneway
from sklearn.metrics import confusion_matrix

# Ensure all_labels and all_probabilities are numpy arrays from previous evaluation cell (d9df1b4b)
# They are already converted to numpy arrays in cell -vhLke3GSj2Y, but let's ensure for this cell's operations.
all_labels = np.array(all_labels, dtype=int) # Ensure integer type
all_probabilities = np.array(all_probabilities)


# 1. Pearson Correlation Coefficient and P-value
# Calculate correlation between true binary labels (0 or 1) and predicted probabilities
# This might not be the most standard use, but can show if higher probabilities correlate with the positive class
pearson_corr, pearson_p_value = pearsonr(all_labels, all_probabilities)
print(f"Pearson Correlation Coefficient between True Labels and Predicted Probabilities: {pearson_corr:.4f}")
print(f"Pearson P-value: {pearson_p_value:.4f}")

# 2. Chi-Square Statistic and P-value
# Applied to the confusion matrix to test for independence between true and predicted classes
conf_matrix = confusion_matrix(all_labels, all_predictions)
chi2_stat, chi2_p_value, _, _ = chi2_contingency(conf_matrix)
print(f"\nChi-Square Statistic on Confusion Matrix: {chi2_stat:.4f}")
print(f"Chi-Square P-value: {chi2_p_value:.4f}")

# 3. ANOVA F-Statistic and P-value
# Compare the mean of predicted probabilities for the positive class between the two true classes
# Separate predicted probabilities based on true class
prob_benign = all_probabilities[all_labels == 0]
prob_malignant = all_probabilities[all_labels == 1]

# Perform one-way ANOVA
# Check if there are enough samples in each group
if len(prob_benign) > 1 and len(prob_malignant) > 1:
    anova_f_statistic, anova_p_value = f_oneway(prob_benign, prob_malignant)
    print(f"\nANOVA F-Statistic (Predicted Probabilities vs. True Class): {anova_f_statistic:.4f}")
    print(f"ANOVA P-value: {anova_p_value:.4f}")
else:
    print("\nNot enough samples in one or both classes to perform ANOVA.")

import torch
import time
import os
import psutil # Library to get system and process information

# Ensure model is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mff.to(device)
model_mff.eval()

# Get a single sample from the test dataset
# Make sure test_dataset is defined from previous steps
if len(test_dataset) > 0:
    sample_input, sample_label = test_dataset[0] # Get the first sample (fixed to unpack 2 values)

    # Add batch dimension and move to device
    sample_input = sample_input.unsqueeze(0).to(device)

    # --- Measure Memory Usage ---
    process = psutil.Process(os.getpid())

    # Initial memory usage
    initial_memory = process.memory_info().rss / (1024 * 1024) # in MB
    print(f"Initial Memory Usage: {initial_memory:.2f} MB")

    # --- Measure Inference Time ---
    # Warm-up run (optional, but good practice for timing)
    with torch.no_grad():
        _ = model_mff(sample_input)

    # Measure time
    start_time = time.time()
    with torch.no_grad():
        output = model_mff(sample_input)
    end_time = time.time()

    inference_time = end_time - start_time
    print(f"Inference Time: {inference_time:.6f} seconds")

    # Peak memory usage during inference is harder to measure precisely within a single script run like this
    # The psutil memory_info().rss gives current resident set size, not peak during a specific operation.
    # More advanced tools or profiling might be needed for accurate peak memory during inference.
    # For simplicity, we'll just print the current memory after inference.
    # Peak memory during inference is generally between initial and final memory if no large objects are freed.
    final_memory = process.memory_info().rss / (1024 * 1024) # in MB
    print(f"Memory Usage After Inference: {final_memory:.2f} MB")

    # A more relevant "Peak Memory" might be the difference if run in isolation or using specific profiling tools.
    # As a rough estimate, one could consider the difference, but it's not truly "peak during inference".
    # print(f"Estimated Memory Increase during Inference: {final_memory - initial_memory:.2f} MB")

else:
    print("Test dataset is empty, cannot measure inference time and memory.")



import torch
import torch.nn.functional as F
import numpy as np
import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

# Ensure the model is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mff.to(device)
model_mff.eval()

# Choose a target layer for Grad-CAM
# We'll use the last convolutional layer before the pooling/classifier
# In ResNet50 backbone (used in MFF_CNN), layer4 is the last convolutional block
target_layer = model_mff.cnn_backbone.layer4[-1] # Use the last block of layer4

# Function to register hooks for Grad-CAM
def register_hooks(model, target_layer):
    # Stores the feature maps
    feature_maps = []
    # Stores the gradients of the target output w.r.t. the feature maps
    gradients = []

    def save_feature_maps(module, input, output):
        feature_maps.append(output)

    def save_gradients(module, grad_in, grad_out):
        # grad_out is a tuple, we need the gradient w.r.t. the output
        gradients.append(grad_out[0])

    # Register hooks
    hook_handle_fm = target_layer.register_forward_hook(save_feature_maps)
    hook_handle_grad = target_layer.register_backward_hook(save_gradients)

    return feature_maps, gradients, hook_handle_fm, hook_handle_grad

# Function to generate Grad-CAM heatmap
def generate_grad_cam(image, model, target_layer, target_class=None):
    feature_maps, gradients, hook_fm, hook_grad = register_hooks(model, target_layer)

    # Add batch dimension and move to device
    input_tensor = image.unsqueeze(0).to(device)

    # Forward pass
    output = model(input_tensor)

    # Get the predicted class
    predicted_class = output.argmax(dim=1).item()

    # If target_class is not specified, use the predicted class
    if target_class is None:
        target_class = predicted_class

    # Zero gradients
    model.zero_grad()

    # Backward pass to get gradients w.r.t. the target class output
    target_output = output[0, target_class]
    target_output.backward()

    # Get the feature maps and gradients
    feature_map = feature_maps[0].squeeze(0)
    gradient = gradients[0].squeeze(0)

    # Deregister hooks
    hook_fm.remove()
    hook_grad.remove()

    # Calculate the weights (global average pooling of gradients)
    weights = torch.mean(gradient, dim=(1, 2), keepdim=True)

    # Compute the CAM
    cam = torch.sum(weights * feature_map, dim=0)

    # Apply ReLU to the CAM
    cam = F.relu(cam)

    # Normalize the CAM to be between 0 and 1
    cam = cam / torch.max(cam)

    # Convert CAM to numpy array and resize to input image size
    cam_np = cam.detach().cpu().numpy()
    h, w = image.shape[1:] # Get original image height and width
    cam_resized = cv2.resize(cam_np, (w, h))

    return cam_resized, predicted_class, target_class

# Function to display the image with Grad-CAM heatmap
def display_grad_cam(image, heatmap, title="Grad-CAM"):
    # Convert image tensor to numpy and denormalize/transpose if needed
    # Assuming image is already normalized and in (C, H, W) format
    # Convert to (H, W, C) and denormalize if necessary for display
    image_np = image.permute(1, 2, 0).cpu().numpy()

    # Denormalize the image if it was normalized (e.g., by dividing by 255.0)
    # If simple_normalize divided by 255, we multiply by 255 here
    # If ToTensorV2 normalized to [0, 1], no denormalization needed here for display

    # Ensure image_np is in uint8 for overlay
    # If image_np is float [0, 1], convert to uint8 [0, 255]
    image_np_uint8 = (image_np * 255).astype(np.uint8)


    # Apply heatmap color map
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)

    # Overlay heatmap on the original image
    # Use cv2.addWeighted for alpha blending
    overlayed_image = cv2.addWeighted(image_np_uint8, 0.6, heatmap_colored, 0.4, 0)

    # Display the images
    fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # Increased figsize


    axes[0].imshow(image_np_uint8)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    axes[1].imshow(heatmap, cmap='jet')
    axes[1].set_title("Grad-CAM Heatmap")
    axes[1].axis('off')

    axes[2].imshow(overlayed_image)
    axes[2].set_title(title)
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

# --- Example Usage ---
# Get a sample image from the test dataset
if len(test_dataset) > 0:
    # Get the first image and label from the test dataset
    sample_image, true_label = test_dataset[0] # Fixed: unpack 2 values
    true_label_name = class_names[true_label] # Get the class name

    print(f"Processing sample with True Label: {true_label_name}")

    # Generate Grad-CAM heatmap for the predicted class
    heatmap, predicted_class_idx, target_class_idx = generate_grad_cam(sample_image, model_mff, target_layer)
    predicted_class_name = class_names[predicted_class_idx]
    target_class_name = class_names[target_class_idx]


    print(f"Model Predicted Class: {predicted_class_name}")
    print(f"Grad-CAM generated for Target Class: {target_class_name}")


    # Display the results
    display_grad_cam(sample_image, heatmap, title=f"Grad-CAM for Predicted Class: {predicted_class_name}")

    # Optional: Generate Grad-CAM for the true class (if different from predicted)
    if predicted_class_idx != true_label:
        print(f"\nGenerating Grad-CAM for True Class: {true_label_name}")
        heatmap_true_class, _, _ = generate_grad_cam(sample_image, model_mff, target_layer, target_class=true_label)
        display_grad_cam(sample_image, heatmap_true_class, title=f"Grad-CAM for True Class: {true_label_name}")


else:
    print("Test dataset is empty, cannot perform Grad-CAM.")

import numpy as np
from sklearn.metrics import confusion_matrix

# Ensure all_labels and all_predictions are available from previous evaluation (cell d9df1b4b)
# all_labels = np.array(...)
# all_predictions = np.array(...)

# Calculate the total number of misclassified samples
misclassified_count = np.sum(all_labels != all_predictions)

print(f"Total number of misclassified samples: {misclassified_count}")

# Get the confusion matrix again to extract FN and FP counts
# Rows are True Labels, Columns are Predicted Labels
# [[TN, FP],
#  [FN, TP]]
conf_matrix = confusion_matrix(all_labels, all_predictions)

tn, fp, fn, tp = conf_matrix.ravel()

print("\nBreakdown of Misclassifications:")
print(f"  False Positives (FP): {fp} (Model predicted Malignant, but it was Benign)")
print(f"  False Negatives (FN): {fn} (Model predicted Benign, but it was Malignant)")

# Calculate Misclassification Rates
# False Positive Rate (FPR): FP / (FP + TN) - Proportion of actual negatives incorrectly classified as positive
# False Negative Rate (FNR): FN / (FN + TP) - Proportion of actual positives incorrectly classified as negative (Type II error)

fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
fnr = fn / (fn + tp) if (fn + tp) > 0 else 0

print("\nMisclassification Rates:")
print(f"  False Positive Rate (FPR): {fpr:.4f}")
print(f"  False Negative Rate (FNR): {fnr:.4f} (Type II Error Rate)")

# Recall (Sensitivity) is 1 - FNR
# Specificity is 1 - FPR
# We've already calculated these in the classification report and specific metrics cell, but reiterating here for clarity
recall_malignant = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity_benign = tn / (tn + fp) if (tn + fp) > 0 else 0

print("\nRelated Metrics for Context:")
print(f"  Recall (Sensitivity) for Malignant: {recall_malignant:.4f}")
print(f"  Specificity for Benign: {specificity_benign:.4f}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure all_probabilities and all_labels are available from previous evaluation (cell d9df1b4b or hG5UgVT59kYz)
# and convert them to numpy arrays if they are lists
all_probabilities = np.array(all_probabilities) # Ensure all_probabilities is a numpy array
all_labels = np.array(all_labels) # Ensure all_labels is a numpy array
all_predictions = np.array(all_predictions) # Ensure all_predictions is a numpy array

# Calculate confidence for the predicted class
# For binary classification, the probability of the predicted class is:
# - all_probabilities for the positive class (malignant)
# - 1 - all_probabilities for the negative class (benign)
predicted_confidences = np.where(all_predictions == 1, all_probabilities, 1 - all_probabilities)

# Separate confidences for correct and incorrect predictions
correctly_predicted_confidences = predicted_confidences[all_labels == all_predictions]
incorrectly_predicted_confidences = predicted_confidences[all_labels != all_predictions]

print("Analysis of Prediction Confidence:")
print(f"  Average confidence for correctly predicted samples: {np.mean(correctly_predicted_confidences):.4f}" if len(correctly_predicted_confidences) > 0 else "  No correctly predicted samples.")
print(f"  Average confidence for incorrectly predicted samples: {np.mean(incorrectly_predicted_confidences):.4f}" if len(incorrectly_predicted_confidences) > 0 else "  No incorrectly predicted samples.")


print("\nConfidence distribution for correctly predicted samples:")
if len(correctly_predicted_confidences) > 0:
    print(f"  Min: {np.min(correctly_predicted_confidences):.4f}")
    print(f"  Max: {np.max(correctly_predicted_confidences):.4f}")
    print(f"  Median: {np.median(correctly_predicted_confidences):.4f}")
    print(f"  Std Dev: {np.std(correctly_predicted_confidences):.4f}")
else:
    print("  No correctly predicted samples to analyze.")


print("\nConfidence distribution for incorrectly predicted samples:")
if len(incorrectly_predicted_confidences) > 0:
    print(f"  Min: {np.min(incorrectly_predicted_confidences):.4f}")
    print(f"  Max: {np.max(incorrectly_predicted_confidences):.4f}")
    print(f"  Median: {np.median(incorrectly_predicted_confidences):.4f}")
    print(f"  Std Dev: {np.std(incorrectly_predicted_confidences):.4f}")
else:
    print("  No incorrectly predicted samples found.")


# Separate confidences by true class
benign_confidences = predicted_confidences[all_labels == 0]
malignant_confidences = predicted_confidences[all_labels == 1]

print("\nConfidence distribution by True Class:")
print(f"  Average confidence for True Benign samples: {np.mean(benign_confidences):.4f}" if len(benign_confidences) > 0 else "  No True Benign samples.")
print(f"  Average confidence for True Malignant samples: {np.mean(malignant_confidences):.4f}" if len(malignant_confidences) > 0 else "  No True Malignant samples.")

print("\nConfidence distribution for True Benign samples:")
if len(benign_confidences) > 0:
    print(f"  Min: {np.min(benign_confidences):.4f}")
    print(f"  Max: {np.max(benign_confidences):.4f}")
    print(f"  Median: {np.median(benign_confidences):.4f}")
    print(f"  Std Dev: {np.std(benign_confidences):.4f}")
else:
    print("  No True Benign samples to analyze.")

print("\nConfidence distribution for True Malignant samples:")
if len(malignant_confidences) > 0:
    print(f"  Min: {np.min(malignant_confidences):.4f}")
    print(f"  Max: {np.max(malignant_confidences):.4f}")
    print(f"  Median: {np.median(malignant_confidences):.4f}")
    print(f"  Std Dev: {np.std(malignant_confidences):.4f}")
else:
    print("  No True Malignant samples to analyze.")

